/**
 * Seed food database — values per 100 g, APPROXIMATE, from general reference knowledge.
 * Every row is seeded as review_status = 'needs_review' and must be verified against a
 * reputable source (e.g. an official Turkish food composition database, subject to its terms
 * of use) before it is relied on. Names in ar/fr are seeded as 'needs_review' too.
 *
 * This file has no runtime imports so scripts can run it directly with Node.
 */
export type FoodCategory =
  | 'grains'
  | 'legumes'
  | 'dairy_egg'
  | 'meat_fish'
  | 'vegetables'
  | 'fruits'
  | 'nuts_seeds'
  | 'fats'
  | 'other';

export type FoodFlag = 'meat' | 'fish' | 'dairy' | 'egg' | 'gluten' | 'honey';

export type UnitKey =
  | 'piece'
  | 'slice'
  | 'tbsp'
  | 'tsp'
  | 'cup'
  | 'glass'
  | 'handful'
  | 'bowl'
  | 'clove'
  | 'bunch'
  | 'portion';

export interface SeedFood {
  key: string;
  category: FoodCategory;
  kcal: number;
  p: number;
  c: number;
  f: number;
  fib: number;
  flags?: FoodFlag[];
  units?: { key: UnitKey; grams: number }[];
  names: { tr: string; en: string; fr: string; ar: string };
}

export const seedFoods: SeedFood[] = [
  // Grains
  {
    key: 'oats',
    category: 'grains',
    kcal: 379,
    p: 13.2,
    c: 67.7,
    f: 6.5,
    fib: 10.1,
    flags: ['gluten'],
    units: [
      { key: 'tbsp', grams: 8 },
      { key: 'cup', grams: 90 },
    ],
    names: { tr: 'Yulaf ezmesi', en: 'Rolled oats', fr: "Flocons d'avoine", ar: 'شوفان' },
  },
  {
    key: 'bulgur',
    category: 'grains',
    kcal: 342,
    p: 12.3,
    c: 75.9,
    f: 1.3,
    fib: 12.5,
    flags: ['gluten'],
    units: [
      { key: 'cup', grams: 170 },
      { key: 'tbsp', grams: 12 },
    ],
    names: { tr: 'Pilavlık bulgur', en: 'Bulgur (dry)', fr: 'Boulgour (sec)', ar: 'برغل خشن' },
  },
  {
    key: 'rice_white',
    category: 'grains',
    kcal: 360,
    p: 6.6,
    c: 79.3,
    f: 0.6,
    fib: 1.0,
    units: [
      { key: 'cup', grams: 180 },
      { key: 'tbsp', grams: 13 },
    ],
    names: {
      tr: 'Pirinç (çiğ)',
      en: 'White rice (dry)',
      fr: 'Riz blanc (cru)',
      ar: 'أرز أبيض (نيء)',
    },
  },
  {
    key: 'bread_whole',
    category: 'grains',
    kcal: 247,
    p: 13,
    c: 41,
    f: 3.4,
    fib: 7,
    flags: ['gluten'],
    units: [{ key: 'slice', grams: 30 }],
    names: {
      tr: 'Tam buğday ekmeği',
      en: 'Wholemeal bread',
      fr: 'Pain complet',
      ar: 'خبز القمح الكامل',
    },
  },
  {
    key: 'bread_white',
    category: 'grains',
    kcal: 266,
    p: 8.9,
    c: 49,
    f: 3.3,
    fib: 2.7,
    flags: ['gluten'],
    units: [{ key: 'slice', grams: 30 }],
    names: { tr: 'Beyaz ekmek', en: 'White bread', fr: 'Pain blanc', ar: 'خبز أبيض' },
  },
  {
    key: 'pasta',
    category: 'grains',
    kcal: 371,
    p: 13,
    c: 75,
    f: 1.5,
    fib: 3.2,
    flags: ['gluten'],
    units: [{ key: 'portion', grams: 80 }],
    names: { tr: 'Makarna (çiğ)', en: 'Pasta (dry)', fr: 'Pâtes (crues)', ar: 'معكرونة (نيئة)' },
  },
  {
    key: 'pasta_whole',
    category: 'grains',
    kcal: 348,
    p: 14.6,
    c: 71,
    f: 1.4,
    fib: 8,
    flags: ['gluten'],
    units: [{ key: 'portion', grams: 80 }],
    names: {
      tr: 'Tam buğday makarna (çiğ)',
      en: 'Wholewheat pasta (dry)',
      fr: 'Pâtes complètes (crues)',
      ar: 'معكرونة قمح كامل (نيئة)',
    },
  },
  {
    key: 'buckwheat',
    category: 'grains',
    kcal: 343,
    p: 13.3,
    c: 71.5,
    f: 3.4,
    fib: 10,
    units: [{ key: 'cup', grams: 170 }],
    names: { tr: 'Karabuğday', en: 'Buckwheat', fr: 'Sarrasin', ar: 'حنطة سوداء' },
  },
  {
    key: 'quinoa',
    category: 'grains',
    kcal: 368,
    p: 14.1,
    c: 64.2,
    f: 6.1,
    fib: 7,
    units: [
      { key: 'cup', grams: 170 },
      { key: 'tbsp', grams: 12 },
    ],
    names: { tr: 'Kinoa (çiğ)', en: 'Quinoa (dry)', fr: 'Quinoa (cru)', ar: 'كينوا (نيئة)' },
  },
  {
    key: 'lavash',
    category: 'grains',
    kcal: 275,
    p: 9,
    c: 55,
    f: 1.5,
    fib: 2.2,
    flags: ['gluten'],
    units: [{ key: 'piece', grams: 60 }],
    names: { tr: 'Lavaş', en: 'Lavash flatbread', fr: 'Pain lavash', ar: 'خبز لواش' },
  },
  {
    key: 'flour_whole',
    category: 'grains',
    kcal: 340,
    p: 13.2,
    c: 72,
    f: 2.5,
    fib: 10.7,
    flags: ['gluten'],
    units: [
      { key: 'tbsp', grams: 10 },
      { key: 'cup', grams: 120 },
    ],
    names: {
      tr: 'Tam buğday unu',
      en: 'Wholemeal flour',
      fr: 'Farine complète',
      ar: 'دقيق القمح الكامل',
    },
  },

  // Legumes
  {
    key: 'chickpeas_cooked',
    category: 'legumes',
    kcal: 164,
    p: 8.9,
    c: 27.4,
    f: 2.6,
    fib: 7.6,
    units: [
      { key: 'cup', grams: 160 },
      { key: 'tbsp', grams: 15 },
    ],
    names: {
      tr: 'Nohut (haşlanmış)',
      en: 'Chickpeas (cooked)',
      fr: 'Pois chiches (cuits)',
      ar: 'حمّص (مسلوق)',
    },
  },
  {
    key: 'lentils_red',
    category: 'legumes',
    kcal: 358,
    p: 23.9,
    c: 63.1,
    f: 2.2,
    fib: 10.8,
    units: [
      { key: 'cup', grams: 190 },
      { key: 'tbsp', grams: 14 },
    ],
    names: {
      tr: 'Kırmızı mercimek (çiğ)',
      en: 'Red lentils (dry)',
      fr: 'Lentilles corail (crues)',
      ar: 'عدس أحمر (نيء)',
    },
  },
  {
    key: 'lentils_green',
    category: 'legumes',
    kcal: 352,
    p: 24.6,
    c: 63.4,
    f: 1.1,
    fib: 10.7,
    units: [{ key: 'cup', grams: 190 }],
    names: {
      tr: 'Yeşil mercimek (çiğ)',
      en: 'Green lentils (dry)',
      fr: 'Lentilles vertes (crues)',
      ar: 'عدس أخضر (نيء)',
    },
  },
  {
    key: 'white_beans_cooked',
    category: 'legumes',
    kcal: 139,
    p: 9.7,
    c: 25.1,
    f: 0.4,
    fib: 6.3,
    units: [{ key: 'cup', grams: 180 }],
    names: {
      tr: 'Kuru fasulye (haşlanmış)',
      en: 'White beans (cooked)',
      fr: 'Haricots blancs (cuits)',
      ar: 'فاصوليا بيضاء (مسلوقة)',
    },
  },

  // Dairy & eggs
  {
    key: 'egg',
    category: 'dairy_egg',
    kcal: 143,
    p: 12.6,
    c: 0.7,
    f: 9.5,
    fib: 0,
    flags: ['egg'],
    units: [{ key: 'piece', grams: 50 }],
    names: { tr: 'Yumurta', en: 'Egg', fr: 'Œuf', ar: 'بيض' },
  },
  {
    key: 'yogurt',
    category: 'dairy_egg',
    kcal: 61,
    p: 3.5,
    c: 4.7,
    f: 3.3,
    fib: 0,
    flags: ['dairy'],
    units: [
      { key: 'bowl', grams: 200 },
      { key: 'tbsp', grams: 20 },
    ],
    names: { tr: 'Yoğurt', en: 'Plain yoghurt', fr: 'Yaourt nature', ar: 'لبن زبادي' },
  },
  {
    key: 'yogurt_strained',
    category: 'dairy_egg',
    kcal: 97,
    p: 9,
    c: 3.9,
    f: 5,
    fib: 0,
    flags: ['dairy'],
    units: [
      { key: 'tbsp', grams: 25 },
      { key: 'bowl', grams: 170 },
    ],
    names: { tr: 'Süzme yoğurt', en: 'Strained yoghurt', fr: 'Yaourt égoutté', ar: 'لبنة' },
  },
  {
    key: 'milk_semi',
    category: 'dairy_egg',
    kcal: 46,
    p: 3.3,
    c: 4.8,
    f: 1.5,
    fib: 0,
    flags: ['dairy'],
    units: [{ key: 'glass', grams: 200 }],
    names: {
      tr: 'Süt (yarım yağlı)',
      en: 'Semi-skimmed milk',
      fr: 'Lait demi-écrémé',
      ar: 'حليب نصف دسم',
    },
  },
  {
    key: 'feta',
    category: 'dairy_egg',
    kcal: 264,
    p: 14.2,
    c: 4.1,
    f: 21.3,
    fib: 0,
    flags: ['dairy'],
    units: [{ key: 'slice', grams: 30 }],
    names: {
      tr: 'Beyaz peynir',
      en: 'White cheese (feta-style)',
      fr: 'Fromage blanc type feta',
      ar: 'جبنة بيضاء',
    },
  },
  {
    key: 'lor',
    category: 'dairy_egg',
    kcal: 98,
    p: 12,
    c: 3.4,
    f: 4,
    fib: 0,
    flags: ['dairy'],
    units: [{ key: 'tbsp', grams: 20 }],
    names: {
      tr: 'Lor peyniri',
      en: 'Lor (whey cheese)',
      fr: 'Lor (fromage de lactosérum)',
      ar: 'جبنة قريش',
    },
  },
  {
    key: 'kashar',
    category: 'dairy_egg',
    kcal: 355,
    p: 26,
    c: 1.5,
    f: 27,
    fib: 0,
    flags: ['dairy'],
    units: [{ key: 'slice', grams: 20 }],
    names: { tr: 'Kaşar peyniri', en: 'Kashar cheese', fr: 'Fromage kaşar', ar: 'جبنة قشقوان' },
  },
  {
    key: 'kefir',
    category: 'dairy_egg',
    kcal: 52,
    p: 3.4,
    c: 4.5,
    f: 2,
    fib: 0,
    flags: ['dairy'],
    units: [{ key: 'glass', grams: 200 }],
    names: { tr: 'Kefir', en: 'Kefir', fr: 'Kéfir', ar: 'كفير' },
  },
  {
    key: 'ayran',
    category: 'dairy_egg',
    kcal: 35,
    p: 1.7,
    c: 2.4,
    f: 1.7,
    fib: 0,
    flags: ['dairy'],
    units: [{ key: 'glass', grams: 200 }],
    names: {
      tr: 'Ayran',
      en: 'Ayran (yoghurt drink)',
      fr: 'Ayran (boisson au yaourt)',
      ar: 'عيران',
    },
  },

  // Meat & fish
  {
    key: 'chicken_breast',
    category: 'meat_fish',
    kcal: 120,
    p: 22.5,
    c: 0,
    f: 2.6,
    fib: 0,
    flags: ['meat'],
    units: [{ key: 'portion', grams: 120 }],
    names: {
      tr: 'Tavuk göğsü (çiğ)',
      en: 'Chicken breast (raw)',
      fr: 'Blanc de poulet (cru)',
      ar: 'صدر دجاج (نيء)',
    },
  },
  {
    key: 'turkey_breast',
    category: 'meat_fish',
    kcal: 114,
    p: 23.7,
    c: 0,
    f: 1.5,
    fib: 0,
    flags: ['meat'],
    units: [{ key: 'portion', grams: 120 }],
    names: {
      tr: 'Hindi göğsü (çiğ)',
      en: 'Turkey breast (raw)',
      fr: 'Blanc de dinde (cru)',
      ar: 'صدر ديك رومي (نيء)',
    },
  },
  {
    key: 'beef_mince',
    category: 'meat_fish',
    kcal: 176,
    p: 20,
    c: 0,
    f: 10,
    fib: 0,
    flags: ['meat'],
    units: [{ key: 'portion', grams: 100 }],
    names: {
      tr: 'Dana kıyma (%10 yağlı)',
      en: 'Beef mince (10% fat)',
      fr: 'Bœuf haché (10 % MG)',
      ar: 'لحم بقري مفروم (10٪ دهون)',
    },
  },
  {
    key: 'salmon',
    category: 'meat_fish',
    kcal: 208,
    p: 20,
    c: 0,
    f: 13,
    fib: 0,
    flags: ['fish'],
    units: [{ key: 'portion', grams: 150 }],
    names: { tr: 'Somon', en: 'Salmon', fr: 'Saumon', ar: 'سلمون' },
  },
  {
    key: 'sea_bass',
    category: 'meat_fish',
    kcal: 97,
    p: 18.4,
    c: 0,
    f: 2,
    fib: 0,
    flags: ['fish'],
    units: [{ key: 'portion', grams: 150 }],
    names: { tr: 'Levrek', en: 'Sea bass', fr: 'Bar (loup)', ar: 'قاروص' },
  },
  {
    key: 'anchovy',
    category: 'meat_fish',
    kcal: 131,
    p: 20.4,
    c: 0,
    f: 4.8,
    fib: 0,
    flags: ['fish'],
    units: [{ key: 'portion', grams: 150 }],
    names: { tr: 'Hamsi', en: 'Anchovies', fr: 'Anchois', ar: 'أنشوفة' },
  },
  {
    key: 'tuna_water',
    category: 'meat_fish',
    kcal: 116,
    p: 25.5,
    c: 0,
    f: 0.8,
    fib: 0,
    flags: ['fish'],
    units: [{ key: 'portion', grams: 80 }],
    names: {
      tr: 'Ton balığı (suda)',
      en: 'Tuna in water',
      fr: 'Thon au naturel',
      ar: 'تونة بالماء',
    },
  },

  // Vegetables
  {
    key: 'tomato',
    category: 'vegetables',
    kcal: 18,
    p: 0.9,
    c: 3.9,
    f: 0.2,
    fib: 1.2,
    units: [{ key: 'piece', grams: 120 }],
    names: { tr: 'Domates', en: 'Tomato', fr: 'Tomate', ar: 'طماطم' },
  },
  {
    key: 'cucumber',
    category: 'vegetables',
    kcal: 15,
    p: 0.7,
    c: 3.6,
    f: 0.1,
    fib: 0.5,
    units: [{ key: 'piece', grams: 150 }],
    names: { tr: 'Salatalık', en: 'Cucumber', fr: 'Concombre', ar: 'خيار' },
  },
  {
    key: 'green_pepper',
    category: 'vegetables',
    kcal: 20,
    p: 0.9,
    c: 4.6,
    f: 0.2,
    fib: 1.7,
    units: [{ key: 'piece', grams: 20 }],
    names: { tr: 'Sivri biber', en: 'Green pepper', fr: 'Piment vert doux', ar: 'فلفل أخضر' },
  },
  {
    key: 'red_pepper',
    category: 'vegetables',
    kcal: 31,
    p: 1,
    c: 6,
    f: 0.3,
    fib: 2.1,
    units: [{ key: 'piece', grams: 150 }],
    names: { tr: 'Kapya biber', en: 'Red pepper', fr: 'Poivron rouge', ar: 'فلفل أحمر' },
  },
  {
    key: 'onion',
    category: 'vegetables',
    kcal: 40,
    p: 1.1,
    c: 9.3,
    f: 0.1,
    fib: 1.7,
    units: [{ key: 'piece', grams: 110 }],
    names: { tr: 'Kuru soğan', en: 'Onion', fr: 'Oignon', ar: 'بصل' },
  },
  {
    key: 'garlic',
    category: 'vegetables',
    kcal: 149,
    p: 6.4,
    c: 33,
    f: 0.5,
    fib: 2.1,
    units: [{ key: 'clove', grams: 4 }],
    names: { tr: 'Sarımsak', en: 'Garlic', fr: 'Ail', ar: 'ثوم' },
  },
  {
    key: 'eggplant',
    category: 'vegetables',
    kcal: 25,
    p: 1,
    c: 5.9,
    f: 0.2,
    fib: 3,
    units: [{ key: 'piece', grams: 250 }],
    names: { tr: 'Patlıcan', en: 'Aubergine', fr: 'Aubergine', ar: 'باذنجان' },
  },
  {
    key: 'zucchini',
    category: 'vegetables',
    kcal: 17,
    p: 1.2,
    c: 3.1,
    f: 0.3,
    fib: 1,
    units: [{ key: 'piece', grams: 200 }],
    names: { tr: 'Kabak', en: 'Courgette', fr: 'Courgette', ar: 'كوسا' },
  },
  {
    key: 'spinach',
    category: 'vegetables',
    kcal: 23,
    p: 2.9,
    c: 3.6,
    f: 0.4,
    fib: 2.2,
    units: [
      { key: 'bunch', grams: 250 },
      { key: 'handful', grams: 30 },
    ],
    names: { tr: 'Ispanak', en: 'Spinach', fr: 'Épinards', ar: 'سبانخ' },
  },
  {
    key: 'broccoli',
    category: 'vegetables',
    kcal: 34,
    p: 2.8,
    c: 6.6,
    f: 0.4,
    fib: 2.6,
    units: [{ key: 'cup', grams: 90 }],
    names: { tr: 'Brokoli', en: 'Broccoli', fr: 'Brocoli', ar: 'بروكلي' },
  },
  {
    key: 'carrot',
    category: 'vegetables',
    kcal: 41,
    p: 0.9,
    c: 9.6,
    f: 0.2,
    fib: 2.8,
    units: [{ key: 'piece', grams: 70 }],
    names: { tr: 'Havuç', en: 'Carrot', fr: 'Carotte', ar: 'جزر' },
  },
  {
    key: 'potato',
    category: 'vegetables',
    kcal: 77,
    p: 2,
    c: 17,
    f: 0.1,
    fib: 2.2,
    units: [{ key: 'piece', grams: 170 }],
    names: { tr: 'Patates', en: 'Potato', fr: 'Pomme de terre', ar: 'بطاطا' },
  },
  {
    key: 'sweet_potato',
    category: 'vegetables',
    kcal: 86,
    p: 1.6,
    c: 20.1,
    f: 0.1,
    fib: 3,
    units: [{ key: 'piece', grams: 150 }],
    names: { tr: 'Tatlı patates', en: 'Sweet potato', fr: 'Patate douce', ar: 'بطاطا حلوة' },
  },
  {
    key: 'lettuce',
    category: 'vegetables',
    kcal: 15,
    p: 1.4,
    c: 2.9,
    f: 0.2,
    fib: 1.3,
    units: [{ key: 'handful', grams: 30 }],
    names: { tr: 'Marul', en: 'Lettuce', fr: 'Laitue', ar: 'خس' },
  },
  {
    key: 'rocket',
    category: 'vegetables',
    kcal: 25,
    p: 2.6,
    c: 3.7,
    f: 0.7,
    fib: 1.6,
    units: [{ key: 'handful', grams: 20 }],
    names: { tr: 'Roka', en: 'Rocket', fr: 'Roquette', ar: 'جرجير' },
  },
  {
    key: 'parsley',
    category: 'vegetables',
    kcal: 36,
    p: 3,
    c: 6.3,
    f: 0.8,
    fib: 3.3,
    units: [
      { key: 'bunch', grams: 50 },
      { key: 'handful', grams: 15 },
    ],
    names: { tr: 'Maydanoz', en: 'Parsley', fr: 'Persil', ar: 'بقدونس' },
  },
  {
    key: 'mushroom',
    category: 'vegetables',
    kcal: 22,
    p: 3.1,
    c: 3.3,
    f: 0.3,
    fib: 1,
    units: [{ key: 'cup', grams: 70 }],
    names: { tr: 'Mantar', en: 'Mushrooms', fr: 'Champignons', ar: 'فطر' },
  },
  {
    key: 'peas',
    category: 'vegetables',
    kcal: 81,
    p: 5.4,
    c: 14.5,
    f: 0.4,
    fib: 5.7,
    units: [{ key: 'cup', grams: 145 }],
    names: { tr: 'Bezelye', en: 'Peas', fr: 'Petits pois', ar: 'بازلاء' },
  },
  {
    key: 'green_beans',
    category: 'vegetables',
    kcal: 31,
    p: 1.8,
    c: 7,
    f: 0.2,
    fib: 2.7,
    units: [{ key: 'cup', grams: 110 }],
    names: { tr: 'Taze fasulye', en: 'Green beans', fr: 'Haricots verts', ar: 'فاصوليا خضراء' },
  },
  {
    key: 'dill',
    category: 'vegetables',
    kcal: 43,
    p: 3.5,
    c: 7,
    f: 1.1,
    fib: 2.1,
    units: [{ key: 'bunch', grams: 40 }],
    names: { tr: 'Dereotu', en: 'Dill', fr: 'Aneth', ar: 'شبت' },
  },
  {
    key: 'spring_onion',
    category: 'vegetables',
    kcal: 32,
    p: 1.8,
    c: 7.3,
    f: 0.2,
    fib: 2.6,
    units: [{ key: 'piece', grams: 15 }],
    names: { tr: 'Taze soğan', en: 'Spring onion', fr: 'Oignon nouveau', ar: 'بصل أخضر' },
  },

  // Fruits
  {
    key: 'apple',
    category: 'fruits',
    kcal: 52,
    p: 0.3,
    c: 13.8,
    f: 0.2,
    fib: 2.4,
    units: [{ key: 'piece', grams: 180 }],
    names: { tr: 'Elma', en: 'Apple', fr: 'Pomme', ar: 'تفاح' },
  },
  {
    key: 'banana',
    category: 'fruits',
    kcal: 89,
    p: 1.1,
    c: 22.8,
    f: 0.3,
    fib: 2.6,
    units: [{ key: 'piece', grams: 120 }],
    names: { tr: 'Muz', en: 'Banana', fr: 'Banane', ar: 'موز' },
  },
  {
    key: 'orange',
    category: 'fruits',
    kcal: 47,
    p: 0.9,
    c: 11.8,
    f: 0.1,
    fib: 2.4,
    units: [{ key: 'piece', grams: 150 }],
    names: { tr: 'Portakal', en: 'Orange', fr: 'Orange', ar: 'برتقال' },
  },
  {
    key: 'lemon',
    category: 'fruits',
    kcal: 29,
    p: 1.1,
    c: 9.3,
    f: 0.3,
    fib: 2.8,
    units: [
      { key: 'piece', grams: 60 },
      { key: 'tbsp', grams: 15 },
    ],
    names: { tr: 'Limon', en: 'Lemon', fr: 'Citron', ar: 'ليمون' },
  },
  {
    key: 'strawberry',
    category: 'fruits',
    kcal: 32,
    p: 0.7,
    c: 7.7,
    f: 0.3,
    fib: 2,
    units: [{ key: 'cup', grams: 150 }],
    names: { tr: 'Çilek', en: 'Strawberries', fr: 'Fraises', ar: 'فراولة' },
  },
  {
    key: 'pomegranate',
    category: 'fruits',
    kcal: 83,
    p: 1.7,
    c: 18.7,
    f: 1.2,
    fib: 4,
    units: [
      { key: 'tbsp', grams: 12 },
      { key: 'cup', grams: 170 },
    ],
    names: { tr: 'Nar', en: 'Pomegranate', fr: 'Grenade', ar: 'رمّان' },
  },
  {
    key: 'dried_fig',
    category: 'fruits',
    kcal: 249,
    p: 3.3,
    c: 63.9,
    f: 0.9,
    fib: 9.8,
    units: [{ key: 'piece', grams: 20 }],
    names: { tr: 'Kuru incir', en: 'Dried fig', fr: 'Figue séchée', ar: 'تين مجفف' },
  },
  {
    key: 'dried_apricot',
    category: 'fruits',
    kcal: 241,
    p: 3.4,
    c: 62.6,
    f: 0.5,
    fib: 7.3,
    units: [{ key: 'piece', grams: 8 }],
    names: { tr: 'Kuru kayısı', en: 'Dried apricot', fr: 'Abricot sec', ar: 'مشمش مجفف' },
  },
  {
    key: 'avocado',
    category: 'fruits',
    kcal: 160,
    p: 2,
    c: 8.5,
    f: 14.7,
    fib: 6.7,
    units: [{ key: 'piece', grams: 150 }],
    names: { tr: 'Avokado', en: 'Avocado', fr: 'Avocat', ar: 'أفوكادو' },
  },
  {
    key: 'date',
    category: 'fruits',
    kcal: 282,
    p: 2.5,
    c: 75,
    f: 0.4,
    fib: 8,
    units: [{ key: 'piece', grams: 8 }],
    names: { tr: 'Hurma', en: 'Dates', fr: 'Dattes', ar: 'تمر' },
  },
  {
    key: 'grapes',
    category: 'fruits',
    kcal: 69,
    p: 0.7,
    c: 18.1,
    f: 0.2,
    fib: 0.9,
    units: [{ key: 'cup', grams: 150 }],
    names: { tr: 'Üzüm', en: 'Grapes', fr: 'Raisin', ar: 'عنب' },
  },

  // Nuts & seeds
  {
    key: 'walnut',
    category: 'nuts_seeds',
    kcal: 654,
    p: 15.2,
    c: 13.7,
    f: 65.2,
    fib: 6.7,
    units: [
      { key: 'piece', grams: 4 },
      { key: 'handful', grams: 25 },
    ],
    names: { tr: 'Ceviz içi', en: 'Walnuts', fr: 'Cerneaux de noix', ar: 'جوز' },
  },
  {
    key: 'almond',
    category: 'nuts_seeds',
    kcal: 579,
    p: 21.2,
    c: 21.6,
    f: 49.9,
    fib: 12.5,
    units: [
      { key: 'piece', grams: 1.2 },
      { key: 'handful', grams: 25 },
    ],
    names: { tr: 'Badem', en: 'Almonds', fr: 'Amandes', ar: 'لوز' },
  },
  {
    key: 'hazelnut',
    category: 'nuts_seeds',
    kcal: 628,
    p: 15,
    c: 16.7,
    f: 60.8,
    fib: 9.7,
    units: [{ key: 'handful', grams: 25 }],
    names: { tr: 'Fındık', en: 'Hazelnuts', fr: 'Noisettes', ar: 'بندق' },
  },
  {
    key: 'tahini',
    category: 'nuts_seeds',
    kcal: 595,
    p: 17,
    c: 21,
    f: 54,
    fib: 9.3,
    units: [{ key: 'tbsp', grams: 15 }],
    names: { tr: 'Tahin', en: 'Tahini', fr: 'Tahini', ar: 'طحينة' },
  },
  {
    key: 'flaxseed',
    category: 'nuts_seeds',
    kcal: 534,
    p: 18.3,
    c: 28.9,
    f: 42.2,
    fib: 27.3,
    units: [{ key: 'tbsp', grams: 10 }],
    names: { tr: 'Keten tohumu', en: 'Flaxseed', fr: 'Graines de lin', ar: 'بذور الكتان' },
  },
  {
    key: 'chia',
    category: 'nuts_seeds',
    kcal: 486,
    p: 16.5,
    c: 42.1,
    f: 30.7,
    fib: 34.4,
    units: [{ key: 'tbsp', grams: 12 }],
    names: { tr: 'Chia tohumu', en: 'Chia seeds', fr: 'Graines de chia', ar: 'بذور الشيا' },
  },
  {
    key: 'pumpkin_seeds',
    category: 'nuts_seeds',
    kcal: 559,
    p: 30.2,
    c: 10.7,
    f: 49,
    fib: 6,
    units: [{ key: 'tbsp', grams: 10 }],
    names: {
      tr: 'Kabak çekirdeği içi',
      en: 'Pumpkin seeds',
      fr: 'Graines de courge',
      ar: 'بذور اليقطين',
    },
  },

  // Fats
  {
    key: 'olive_oil',
    category: 'fats',
    kcal: 884,
    p: 0,
    c: 0,
    f: 100,
    fib: 0,
    units: [
      { key: 'tbsp', grams: 13 },
      { key: 'tsp', grams: 4.5 },
    ],
    names: { tr: 'Zeytinyağı', en: 'Olive oil', fr: "Huile d'olive", ar: 'زيت زيتون' },
  },
  {
    key: 'butter',
    category: 'fats',
    kcal: 717,
    p: 0.9,
    c: 0.1,
    f: 81,
    fib: 0,
    flags: ['dairy'],
    units: [
      { key: 'tsp', grams: 5 },
      { key: 'tbsp', grams: 14 },
    ],
    names: { tr: 'Tereyağı', en: 'Butter', fr: 'Beurre', ar: 'زبدة' },
  },
  {
    key: 'green_olive',
    category: 'fats',
    kcal: 145,
    p: 1,
    c: 3.8,
    f: 15.3,
    fib: 3.3,
    units: [{ key: 'piece', grams: 4 }],
    names: { tr: 'Yeşil zeytin', en: 'Green olives', fr: 'Olives vertes', ar: 'زيتون أخضر' },
  },

  // Other
  {
    key: 'honey',
    category: 'other',
    kcal: 304,
    p: 0.3,
    c: 82.4,
    f: 0,
    fib: 0.2,
    flags: ['honey'],
    units: [{ key: 'tsp', grams: 7 }],
    names: { tr: 'Bal', en: 'Honey', fr: 'Miel', ar: 'عسل' },
  },
  {
    key: 'grape_molasses',
    category: 'other',
    kcal: 293,
    p: 0.5,
    c: 72,
    f: 0.3,
    fib: 0,
    units: [
      { key: 'tsp', grams: 7 },
      { key: 'tbsp', grams: 20 },
    ],
    names: { tr: 'Üzüm pekmezi', en: 'Grape molasses', fr: 'Mélasse de raisin', ar: 'دبس العنب' },
  },
  {
    key: 'tomato_paste',
    category: 'other',
    kcal: 82,
    p: 4.3,
    c: 18.9,
    f: 0.5,
    fib: 4.1,
    units: [{ key: 'tbsp', grams: 16 }],
    names: {
      tr: 'Domates salçası',
      en: 'Tomato paste',
      fr: 'Concentré de tomate',
      ar: 'معجون طماطم',
    },
  },
  {
    key: 'pepper_paste',
    category: 'other',
    kcal: 90,
    p: 3,
    c: 16,
    f: 1,
    fib: 4,
    units: [{ key: 'tbsp', grams: 16 }],
    names: { tr: 'Biber salçası', en: 'Red pepper paste', fr: 'Purée de piment', ar: 'دبس الفلفل' },
  },
  {
    key: 'cinnamon',
    category: 'other',
    kcal: 247,
    p: 4,
    c: 80.6,
    f: 1.2,
    fib: 53.1,
    units: [{ key: 'tsp', grams: 2.6 }],
    names: { tr: 'Tarçın', en: 'Cinnamon', fr: 'Cannelle', ar: 'قرفة' },
  },
  {
    key: 'cumin',
    category: 'other',
    kcal: 375,
    p: 17.8,
    c: 44.2,
    f: 22.3,
    fib: 10.5,
    units: [{ key: 'tsp', grams: 2 }],
    names: { tr: 'Kimyon', en: 'Cumin', fr: 'Cumin', ar: 'كمون' },
  },
  {
    key: 'chili_flakes',
    category: 'other',
    kcal: 282,
    p: 13.5,
    c: 49.7,
    f: 14.3,
    fib: 34.8,
    units: [{ key: 'tsp', grams: 2 }],
    names: {
      tr: 'Pul biber',
      en: 'Chilli flakes (pul biber)',
      fr: 'Piment en flocons (pul biber)',
      ar: 'فلفل أحمر مجروش',
    },
  },
  {
    key: 'mint_dried',
    category: 'other',
    kcal: 285,
    p: 19.9,
    c: 52,
    f: 6,
    fib: 29.8,
    units: [{ key: 'tsp', grams: 1 }],
    names: { tr: 'Kuru nane', en: 'Dried mint', fr: 'Menthe séchée', ar: 'نعناع مجفف' },
  },
  {
    key: 'sumac',
    category: 'other',
    kcal: 239,
    p: 4.4,
    c: 42,
    f: 13.8,
    fib: 28,
    units: [{ key: 'tsp', grams: 2 }],
    names: { tr: 'Sumak', en: 'Sumac', fr: 'Sumac', ar: 'سماق' },
  },
  {
    key: 'dark_chocolate',
    category: 'other',
    kcal: 598,
    p: 7.8,
    c: 45.9,
    f: 42.6,
    fib: 10.9,
    flags: ['dairy'],
    units: [{ key: 'piece', grams: 10 }],
    names: {
      tr: 'Bitter çikolata (%70+)',
      en: 'Dark chocolate (70%+)',
      fr: 'Chocolat noir (70 %+)',
      ar: 'شوكولاتة داكنة (70٪+)',
    },
  },
];
