-- GENERATED by scripts/gen-seed.ts — FICTIONAL DEMO DATA for local mode only.
-- Never run against a production database.
do $demo$
declare
  v_owner uuid;
begin
  select id into v_owner from public.profiles where role = 'dietitian' order by created_at limit 1;

  insert into public.clients (id, owner_id, full_name, email, phone, birth_date, sex, height_cm, goal, goal_weight_kg, activity_level, allergies, medical_notes, preferred_language, status, tags, source, kvkk_consent_at, kvkk_consent_version, created_at) values
    ('8c333d28-8e6c-5635-946c-1e3d9066554c', v_owner, 'Deniz Aksoy (demo)', 'deniz.demo@example.com', '+905550000001', '1991-04-12', 'female', 166, 'Düzenli öğün saatleri, enerjinin gün içinde dengelenmesi.', 64, 'light', 'Laktoz intoleransı (hafif)', 'Demo tıbbi not — paylaşım sayfasında görünmemeli.', 'tr', 'active', '{"online","ofis"}'::text[], 'demo', now() - interval '98 days', 'kvkk-2026-01', now() - interval '98 days'),
    ('e0dfed6d-9351-53a5-9efd-6960f459309f', v_owner, 'Emre Yıldız (demo)', 'emre.demo@example.com', '+905550000002', '1986-09-30', 'male', 181, 'Koşu antrenmanlarına uygun beslenme.', null, 'active', null, null, 'tr', 'active', '{"sporcu"}'::text[], 'demo', now() - interval '70 days', 'kvkk-2026-01', now() - interval '70 days'),
    ('82874080-9118-558c-a40b-6ebebb298afc', v_owner, 'Layla Haddad (demo)', 'layla.demo@example.com', '+905550000003', '1995-01-18', 'female', 160, 'Aile sofrasını düzenlemek, sebze tüketimini artırmak.', 58, 'moderate', null, null, 'ar', 'active', '{"aile"}'::text[], 'demo', now() - interval '56 days', 'kvkk-2026-01', now() - interval '56 days'),
    ('422ac089-f6c4-5897-87f6-99c47a01879d', v_owner, 'Camille Martin (demo)', 'camille.demo@example.com', '+905550000004', '1989-06-03', 'female', 170, 'Vejetaryen beslenmede protein dengesi.', null, 'moderate', null, null, 'fr', 'active', '{"vejetaryen","online"}'::text[], 'demo', now() - interval '42 days', 'kvkk-2026-01', now() - interval '42 days'),
    ('6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', v_owner, 'Mert Kaya (demo)', 'mert.demo@example.com', '+905550000005', '1979-11-22', 'male', 175, 'Sürdürülebilir kilo kaybı, akşam atıştırmalarını azaltmak.', 84, 'sedentary', null, 'Demo: hekim takibinde; ilaç bilgisi hekimde.', 'tr', 'active', '{"ofis"}'::text[], 'demo', now() - interval '126 days', 'kvkk-2026-01', now() - interval '126 days'),
    ('47604d66-cdda-59ec-a579-67a5a14abe60', v_owner, 'Selin Öztürk (demo)', 'selin.demo@example.com', '+905550000006', '1998-02-14', 'female', 163, 'Kahvaltı alışkanlığı kazanmak.', null, 'light', null, null, 'en', 'paused', '{}'::text[], 'demo', now() - interval '28 days', 'kvkk-2026-01', now() - interval '28 days'),
    ('48c4e28a-a22d-5c7a-800d-90b20024e41e', v_owner, 'Ahmet Demir (demo)', 'ahmet.demo@example.com', '+905550000007', '1970-07-07', 'male', 172, 'Tamamlandı: düzenli beslenme.', 80, 'light', null, null, 'tr', 'completed', '{}'::text[], 'demo', now() - interval '140 days', 'kvkk-2026-01', now() - interval '140 days');

  insert into public.measurements (id, owner_id, client_id, measured_at, weight_kg, body_fat_pct, waist_cm, hip_cm) values
    ('7ed72c8b-7bf2-5224-84ec-3a0a1addfa10', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '2026-06-10', 71.4, 29.1, 78.2, 96.2),
    ('78b54e7e-4b37-5132-bd82-588978faca19', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '2026-06-24', 70.4, 28.7, 77.5, 95.5),
    ('fd9c156a-0770-5ada-a13d-c4ff08f0de01', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '2026-07-08', 69.8, 28.4, 77.2, 95.2),
    ('1a2bf24f-ce16-51dc-8302-46d1fd313707', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '2026-07-22', 69.2, 28.2, 76.8, 94.8),
    ('30b5192d-b84d-5a4f-96ef-8447ad005dff', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '2026-08-05', 68.2, 27.8, 76.1, 94.1),
    ('45039419-154a-50ee-aa4b-faa19094cbe4', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '2026-08-19', 67.9, 27.7, 76.1, 94.1),
    ('37fdf38e-9b5f-5ca2-aa7f-22b0ec7f2336', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '2026-09-02', 66.7, 27.2, 75.2, 93.2),
    ('ed227e58-6064-5e14-9bf0-b9d08774b374', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '2026-09-16', 66.6, 27.2, 75.4, 93.4),
    ('f0542a60-7e9f-5ba1-a9f9-3b9fc8046568', v_owner, 'e0dfed6d-9351-53a5-9efd-6960f459309f', '2026-07-24', 78.1, 21.8, 91.7, 109.7),
    ('cc50acf8-ff9a-5771-a7ff-503300a131d2', v_owner, 'e0dfed6d-9351-53a5-9efd-6960f459309f', '2026-08-07', 78.8, 22.2, 92.3, 110.3),
    ('f6443843-5a83-557f-9d96-620ec122d076', v_owner, 'e0dfed6d-9351-53a5-9efd-6960f459309f', '2026-08-21', 78.4, 22, 91.9, 109.9),
    ('6f5348cb-8285-58d8-b74e-f412622eea93', v_owner, 'e0dfed6d-9351-53a5-9efd-6960f459309f', '2026-09-04', 78.8, 22.2, 92.3, 110.3),
    ('42d470c1-effb-51a4-9e4e-a9dd6b25fb9c', v_owner, 'e0dfed6d-9351-53a5-9efd-6960f459309f', '2026-09-18', 78.7, 22.1, 92.2, 110.2),
    ('77b7e3f9-ba7b-5de5-85a0-5715b9a8c13d', v_owner, 'e0dfed6d-9351-53a5-9efd-6960f459309f', '2026-10-02', 78.9, 22.2, 92.3, 110.3),
    ('a199ff61-e5c6-57d6-9adf-16d7ff132c6c', v_owner, '82874080-9118-558c-a40b-6ebebb298afc', '2026-08-07', 63.1, 29, 78.1, 96.1),
    ('c05a0042-4c5a-5393-a16f-8e2c5eecced6', v_owner, '82874080-9118-558c-a40b-6ebebb298afc', '2026-08-21', 62.6, 28.8, 77.8, 95.8),
    ('2d69f1f0-56fc-584c-b54f-b2e823010666', v_owner, '82874080-9118-558c-a40b-6ebebb298afc', '2026-09-04', 62.1, 28.6, 77.4, 95.4),
    ('0f28dbba-9c5d-5c48-895a-912258651205', v_owner, '82874080-9118-558c-a40b-6ebebb298afc', '2026-09-18', 62, 28.6, 77.5, 95.5),
    ('3bbdb414-6de0-5bcf-a2d4-458d3e086827', v_owner, '82874080-9118-558c-a40b-6ebebb298afc', '2026-10-02', 61.1, 28.2, 76.8, 94.8),
    ('c13af80f-9d68-5946-8e4a-5ff5f9865714', v_owner, '422ac089-f6c4-5897-87f6-99c47a01879d', '2026-08-21', 61.6, 29.1, 78.1, 96.1),
    ('35ec8513-54f3-58b0-915f-918df0d01aa0', v_owner, '422ac089-f6c4-5897-87f6-99c47a01879d', '2026-09-04', 61.3, 28.9, 77.8, 95.8),
    ('3bd82c12-623d-5333-a491-8eb884d0b4fe', v_owner, '422ac089-f6c4-5897-87f6-99c47a01879d', '2026-09-18', 61.8, 29.2, 78.3, 96.3),
    ('c9b29a02-98b0-5869-879e-bbbf81426e7c', v_owner, '422ac089-f6c4-5897-87f6-99c47a01879d', '2026-10-02', 61.3, 28.9, 77.8, 95.8),
    ('b55564f9-4155-5af1-97ae-0cbfbd5b5d91', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', '2026-05-29', 96.5, 21.9, 91.7, 109.7),
    ('ad5955bc-fa60-5bf9-8e69-c249af4c24e1', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', '2026-06-12', 96.1, 21.7, 91.7, 109.7),
    ('f30b4187-cd88-5ff3-8750-62e53901065b', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', '2026-06-26', 94.9, 21.2, 90.8, 108.8),
    ('35c777bf-a6d8-51d4-9835-54912e95903f', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', '2026-07-10', 94.2, 20.9, 90.4, 108.4),
    ('82c8c81b-54ea-58e7-92b0-96d3bd979f65', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', '2026-07-24', 93.2, 20.6, 89.9, 107.9),
    ('f7cfdcc5-3c3e-5e5d-9594-2c93e987d6b4', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', '2026-08-07', 92.2, 20.1, 89.2, 107.2),
    ('6b625816-1b49-576e-b953-ffbffec4f9cd', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', '2026-08-21', 91.6, 19.9, 89, 107),
    ('ffa25fcd-666c-595d-a466-728c281a269a', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', '2026-09-04', 90.2, 19.3, 88, 106),
    ('e4760cbd-f466-5b4a-b26f-d2608da02593', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', '2026-09-18', 89.9, 19.3, 88, 106),
    ('cdab4644-b933-51ef-b6d7-fe1708503288', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', '2026-10-02', 88.4, 18.6, 86.8, 104.8),
    ('54d5e94e-3541-5bf9-aa31-4ec419f58991', v_owner, '47604d66-cdda-59ec-a579-67a5a14abe60', '2026-09-04', 54.9, 28.9, 77.9, 95.9),
    ('1cc3dd41-8c71-57ff-a736-9548c2bb31b1', v_owner, '47604d66-cdda-59ec-a579-67a5a14abe60', '2026-09-18', 55, 29, 78, 96),
    ('6a2d72bf-7346-583f-a94e-5f58e0300679', v_owner, '47604d66-cdda-59ec-a579-67a5a14abe60', '2026-10-02', 55.1, 29, 78.1, 96.1),
    ('3f7b9a89-71f3-52ba-bd88-6c05c357773c', v_owner, '48c4e28a-a22d-5c7a-800d-90b20024e41e', '2026-05-15', 86.2, 22.1, 92.2, 110.2),
    ('ffeeab82-aabd-5415-852d-7981d3a2d0c3', v_owner, '48c4e28a-a22d-5c7a-800d-90b20024e41e', '2026-05-29', 85.2, 21.7, 91.5, 109.5),
    ('4219c265-2a73-5cd3-9e1a-967d13152871', v_owner, '48c4e28a-a22d-5c7a-800d-90b20024e41e', '2026-06-12', 84.9, 21.6, 91.4, 109.4),
    ('f392587b-e8c2-5ed1-a5c6-44d3a41bbcc2', v_owner, '48c4e28a-a22d-5c7a-800d-90b20024e41e', '2026-06-26', 84.2, 21.3, 90.9, 108.9),
    ('6f677c4b-ec2c-5f54-b230-8e44d01a9ec3', v_owner, '48c4e28a-a22d-5c7a-800d-90b20024e41e', '2026-07-10', 83.5, 21, 90.5, 108.5),
    ('9d194d70-55ef-5f95-afb3-8ffd25bc0cb7', v_owner, '48c4e28a-a22d-5c7a-800d-90b20024e41e', '2026-07-24', 83.2, 20.9, 90.4, 108.4),
    ('3e5972db-86b6-5846-970b-20befb8bf1a5', v_owner, '48c4e28a-a22d-5c7a-800d-90b20024e41e', '2026-08-07', 82.2, 20.4, 89.6, 107.6),
    ('11e3d4b7-f2f0-5181-9b30-c918d8f2059c', v_owner, '48c4e28a-a22d-5c7a-800d-90b20024e41e', '2026-08-21', 82.1, 20.5, 89.8, 107.8),
    ('3f9ba5d5-6c3b-5abe-a773-22b4a00c9bc7', v_owner, '48c4e28a-a22d-5c7a-800d-90b20024e41e', '2026-09-04', 80.9, 19.9, 88.8, 106.8),
    ('fbcd20e4-e872-5d20-8c48-eab353c08056', v_owner, '48c4e28a-a22d-5c7a-800d-90b20024e41e', '2026-09-18', 80.9, 20, 89.1, 107.1),
    ('181d862d-b14b-5c27-a9fe-affdad2c9c6e', v_owner, '48c4e28a-a22d-5c7a-800d-90b20024e41e', '2026-10-02', 79.7, 19.4, 88.1, 106.1);

  insert into public.client_notes (id, owner_id, client_id, body, pinned, created_at) values
    ('37b2f304-f1b6-570b-ad07-d36141235e97', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', 'İlk görüşme: kahvaltıyı genellikle atlıyor, öğleden sonra enerji düşüşü yaşıyor. Hedef: önce saatleri sabitlemek.', true, now() - interval '98 days'),
    ('f778a4c1-0634-52db-bcfd-87e0fecb46b6', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', 'Kahvaltı 5/7 gün yapılıyor. Akşam atıştırmaları azaldı. Sebze tüketimi hâlâ düşük.', false, now() - interval '40 days'),
    ('96aa39dd-c82e-544e-a08e-701ac2d10e10', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', 'Akşam 22:00 sonrası atıştırma alışkanlığı. İkindiye proteinli ara öğün eklendi.', true, now() - interval '60 days'),
    ('a0080c40-2672-53c0-8446-531e1ded0bf3', v_owner, '82874080-9118-558c-a40b-6ebebb298afc', 'Program Arapça hazırlanacak. Çocuklar için de uygun tarifler istiyor.', true, now() - interval '50 days');

  insert into public.programs (id, owner_id, client_id, title, language, status, starts_on, target_kcal, target_protein_g, target_carb_g, target_fat_g, notes, hydration) values
    ('754274d3-6afe-5580-b37e-880bc48c494f', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', 'Eylül — düzenli öğünler', 'tr', 'active', current_date - 3, 1800, 90, 200, 60,
     'Öğün saatlerini sabit tutmaya çalış; bir öğünü kaçırırsan bir sonrakini büyütmek yerine planına dön.',
     'Her öğünden önce bir bardak su. Gün içinde toplam 8–10 bardak hedefle; çay ve kahveyi şekersiz tercih et.'),
    ('a65a3ccd-bbdf-5600-9c3d-122423909eda', v_owner, null, 'Dengeli hafta', 'tr', 'draft', null, 1900, 95, 210, 65, null, null);
  update public.programs set is_template = true where id = 'a65a3ccd-bbdf-5600-9c3d-122423909eda';
  insert into public.program_days (id, owner_id, program_id, position, label) values
    ('4de56585-f1a6-553e-958e-ce110d8b34c3', v_owner, 'a65a3ccd-bbdf-5600-9c3d-122423909eda', 0, null),
    ('e626b55e-1349-552e-baa4-e0a8a1ace823', v_owner, 'a65a3ccd-bbdf-5600-9c3d-122423909eda', 1, null),
    ('f2936a10-9839-5706-83fc-2e858351576e', v_owner, 'a65a3ccd-bbdf-5600-9c3d-122423909eda', 2, null),
    ('af54f127-8cf9-5304-8378-28f95b5fb482', v_owner, 'a65a3ccd-bbdf-5600-9c3d-122423909eda', 3, null),
    ('942d4a56-6177-5f25-8691-d3c697f715b8', v_owner, 'a65a3ccd-bbdf-5600-9c3d-122423909eda', 4, null),
    ('319f1188-198a-5a14-9c5a-c91288a14cec', v_owner, 'a65a3ccd-bbdf-5600-9c3d-122423909eda', 5, null),
    ('dcac545b-fd23-5396-a9e4-e226786e6fd5', v_owner, 'a65a3ccd-bbdf-5600-9c3d-122423909eda', 6, null);

  insert into public.program_days (id, owner_id, program_id, position, label) values
    ('1f7b9830-1fd7-57bf-b107-99ba0060d3bf', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 0, null),
    ('fd415242-7abc-5ac9-a719-ade77a1e54b9', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 1, null),
    ('c9d22938-96ef-5224-97bb-dbb690ac2b93', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 2, null),
    ('fc95c1ce-27b7-5c10-978b-646dd5ea3d96', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 3, null),
    ('cf780b46-893a-50a2-9b3e-70c36ec7c5cf', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 4, null),
    ('cc26f09f-ebda-5870-9054-c25e5d5f27c1', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 5, null),
    ('f0fc3a7f-1596-59dc-939b-0932c9a029ee', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 6, null);
  insert into public.program_meals (id, owner_id, program_id, day_id, slot, position, time_label, note) values
    ('038a2963-bc60-542f-9456-b7ecf22a22e2', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '1f7b9830-1fd7-57bf-b107-99ba0060d3bf', 'breakfast', 0, '08:00', null),
    ('ae6d4076-3327-5510-813c-0e18f3c7e357', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '1f7b9830-1fd7-57bf-b107-99ba0060d3bf', 'lunch', 1, '13:00', null),
    ('741aef89-0ebc-512c-b679-73163f92e08b', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '1f7b9830-1fd7-57bf-b107-99ba0060d3bf', 'snack_pm', 2, '16:30', null),
    ('8455d828-627a-571f-a250-8b91087dcd23', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '1f7b9830-1fd7-57bf-b107-99ba0060d3bf', 'dinner', 3, '19:30', null),
    ('2a728122-1ad2-51d5-a4e8-6905ee2016be', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'fd415242-7abc-5ac9-a719-ade77a1e54b9', 'breakfast', 0, '08:00', null),
    ('42496ac6-2cc5-57e9-97d8-f8190a72d552', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'fd415242-7abc-5ac9-a719-ade77a1e54b9', 'lunch', 1, '13:00', null),
    ('891527b9-c1fe-5c0d-acc9-108985a293ae', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'fd415242-7abc-5ac9-a719-ade77a1e54b9', 'snack_pm', 2, '16:30', null),
    ('7596c0f2-df06-5920-9572-1753798ed71b', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'fd415242-7abc-5ac9-a719-ade77a1e54b9', 'dinner', 3, '19:30', null),
    ('defc0133-47a3-59ab-8afb-32d19fed105a', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'c9d22938-96ef-5224-97bb-dbb690ac2b93', 'breakfast', 0, '08:00', null),
    ('722ad53f-d206-509c-a394-20bba39e7d90', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'c9d22938-96ef-5224-97bb-dbb690ac2b93', 'lunch', 1, '13:00', null),
    ('adb5bf9f-f9e4-5ad0-aa90-eece99e3acfd', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'c9d22938-96ef-5224-97bb-dbb690ac2b93', 'snack_pm', 2, '16:30', null),
    ('de030006-d394-560e-bb40-5aacd310dcf6', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'c9d22938-96ef-5224-97bb-dbb690ac2b93', 'dinner', 3, '19:30', null),
    ('a8b3ffbd-c164-584d-8697-8f3dead9fc7d', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'fc95c1ce-27b7-5c10-978b-646dd5ea3d96', 'breakfast', 0, '08:00', null),
    ('1f7f3f97-afe0-575e-ae17-165ed277272b', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'fc95c1ce-27b7-5c10-978b-646dd5ea3d96', 'lunch', 1, '13:00', null),
    ('9021d3a2-d1f6-5160-9175-96aaa07e2b6e', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'fc95c1ce-27b7-5c10-978b-646dd5ea3d96', 'snack_pm', 2, '16:30', null),
    ('cbacffaa-c734-5987-9f0c-5f5a320ceb66', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'fc95c1ce-27b7-5c10-978b-646dd5ea3d96', 'dinner', 3, '19:30', null),
    ('2233892e-0b2e-5b4b-88ed-a2ae23b91fab', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'cf780b46-893a-50a2-9b3e-70c36ec7c5cf', 'breakfast', 0, '08:00', null),
    ('eaa28ac4-fb9f-511a-975e-4670b3dafdc0', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'cf780b46-893a-50a2-9b3e-70c36ec7c5cf', 'lunch', 1, '13:00', null),
    ('dde4729e-3523-5f8e-a63d-d178d184d412', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'cf780b46-893a-50a2-9b3e-70c36ec7c5cf', 'snack_pm', 2, '16:30', null),
    ('aa1282d9-1ed8-5048-a8f9-a508e31f4683', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'cf780b46-893a-50a2-9b3e-70c36ec7c5cf', 'dinner', 3, '19:30', null),
    ('b125b348-a26c-5132-8dc5-f795d11aa069', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'cc26f09f-ebda-5870-9054-c25e5d5f27c1', 'breakfast', 0, '08:00', null),
    ('9ac0d4cb-d522-50ed-9133-1a37db11514c', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'cc26f09f-ebda-5870-9054-c25e5d5f27c1', 'lunch', 1, '13:00', null),
    ('def28902-6dce-5bf2-aa71-e28c4076e7af', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'cc26f09f-ebda-5870-9054-c25e5d5f27c1', 'snack_pm', 2, '16:30', null),
    ('bf92ecfa-070f-5ef0-820a-2e59f3e96935', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'cc26f09f-ebda-5870-9054-c25e5d5f27c1', 'dinner', 3, '19:30', null),
    ('595d2fb5-1737-59b3-b266-8fea4fe63015', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'f0fc3a7f-1596-59dc-939b-0932c9a029ee', 'breakfast', 0, '08:00', null),
    ('f998614b-6fb7-5e1e-8735-aaa6e2f12d36', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'f0fc3a7f-1596-59dc-939b-0932c9a029ee', 'lunch', 1, '13:00', null),
    ('5cf153f0-95e5-50cb-9282-648c6ce5cc1f', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'f0fc3a7f-1596-59dc-939b-0932c9a029ee', 'snack_pm', 2, '16:30', null),
    ('7ee0f54b-8986-5eaf-a3c3-3d3fb1d84713', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'f0fc3a7f-1596-59dc-939b-0932c9a029ee', 'dinner', 3, '19:30', null);
  insert into public.program_meal_items (id, owner_id, program_id, meal_id, food_id, recipe_id, name, grams, unit_key, unit_qty, servings, kcal, protein_g, carb_g, fat_g, fiber_g, position) values
    ('6a6226a0-a00c-5f3b-b5b9-a502cff4db1f', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '038a2963-bc60-542f-9456-b7ecf22a22e2', null, '9b0af6b0-397a-50ab-927d-8a627c1cb983', 'Süzme yoğurtlu gece yulafı', null, null, null, 1, 398, 21.1, 39.9, 18.2, 6.3, 0),
    ('5dd1bfd9-c8fc-5de1-849f-13e954efc1d8', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '038a2963-bc60-542f-9456-b7ecf22a22e2', '0cab1e9f-8d2e-5024-9fe1-9ea6a172133e', null, 'Tam buğday ekmeği', 30, 'slice', 1, null, 74.1, 3.9, 12.3, 1, 2.1, 1),
    ('15f1936a-c07c-5b1d-8820-21aab0bbcde9', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'ae6d4076-3327-5510-813c-0e18f3c7e357', null, '23c9cd4c-4d42-5a1c-84a4-7ba0815d98a0', 'Nohutlu kinoa salatası', null, null, null, 1, 383.9, 14.9, 58.6, 11.7, 12, 0),
    ('2478917f-cac9-5c37-a369-b83992648dd0', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'ae6d4076-3327-5510-813c-0e18f3c7e357', '0cab1e9f-8d2e-5024-9fe1-9ea6a172133e', null, 'Tam buğday ekmeği', 30, 'slice', 1, null, 74.1, 3.9, 12.3, 1, 2.1, 1),
    ('25ca3faf-9407-5987-9188-56157c536819', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '741aef89-0ebc-512c-b679-73163f92e08b', null, 'ce6fe68f-4009-59ff-8481-923621dfc45e', 'Elmalı, tarçınlı süzme yoğurt', null, null, null, 1, 276.3, 16, 22.7, 14.8, 5.3, 0),
    ('2bcb92e4-23cf-59cc-abf9-d0d20b7b572f', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '8455d828-627a-571f-a250-8b91087dcd23', null, '23d45a3e-ec05-5547-a44b-01fe1b82523c', 'Fırında limonlu somon ve kabak', null, null, null, 1, 422.4, 33.3, 11, 26.8, 3.1, 0),
    ('bf2ecadd-945f-50b1-882a-3b04dd5ffb74', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '2a728122-1ad2-51d5-a4e8-6905ee2016be', null, '395caa3a-20d2-55f1-9ef6-ad2c21bfe191', 'Menemen', null, null, null, 1, 204.5, 11.4, 9.2, 14.1, 2.8, 0),
    ('9d006be6-eb20-50e5-972a-308050a575ee', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '2a728122-1ad2-51d5-a4e8-6905ee2016be', '0cab1e9f-8d2e-5024-9fe1-9ea6a172133e', null, 'Tam buğday ekmeği', 30, 'slice', 1, null, 74.1, 3.9, 12.3, 1, 2.1, 1),
    ('2b39ddf3-fa12-55e8-977e-373eed440abe', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '42496ac6-2cc5-57e9-97d8-f8190a72d552', null, 'df15333a-90d0-5b10-8011-89bbb352c405', 'Kırmızı mercimek çorbası', null, null, null, 1, 253, 12.2, 35.9, 7.8, 6.5, 0),
    ('ea2469da-0f7e-546e-b129-1f5d7440fc89', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '42496ac6-2cc5-57e9-97d8-f8190a72d552', '0cab1e9f-8d2e-5024-9fe1-9ea6a172133e', null, 'Tam buğday ekmeği', 30, 'slice', 1, null, 74.1, 3.9, 12.3, 1, 2.1, 1),
    ('91e6b345-6f10-5121-916e-9cd4ca484663', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '891527b9-c1fe-5c0d-acc9-108985a293ae', null, 'bda683e7-26ac-53ac-9486-de9ee4253c5f', 'Fırında baharatlı nohut', null, null, null, 1, 230, 10.9, 33.6, 6.6, 9.5, 0),
    ('1e5d2811-6cb1-553e-948b-354b53d3af8e', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '7596c0f2-df06-5920-9572-1753798ed71b', null, 'b9507c06-8136-5950-bcd1-120f57d33429', 'Tavuklu sebze sote', null, null, null, 1, 292.5, 33.2, 16.6, 10.6, 4.5, 0),
    ('75223f36-fccb-5ebf-960b-742a85778258', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'defc0133-47a3-59ab-8afb-32d19fed105a', null, 'e7fbf28f-0734-55d3-b1fd-e1f54b181c7d', 'Çılbır', null, null, null, 1, 245.7, 16.4, 6.6, 17, 0.4, 0),
    ('a0c70215-e1fb-54d5-98e8-0c30e9086496', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'defc0133-47a3-59ab-8afb-32d19fed105a', '0cab1e9f-8d2e-5024-9fe1-9ea6a172133e', null, 'Tam buğday ekmeği', 30, 'slice', 1, null, 74.1, 3.9, 12.3, 1, 2.1, 1),
    ('1fc1823f-f5b6-51ff-950c-a15157beb31b', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '722ad53f-d206-509c-a394-20bba39e7d90', null, '0a9df7e3-db0f-5cd9-b3c0-adee7b81f04c', 'Ton balıklı piyaz', null, null, null, 1, 433.5, 39.3, 52.7, 8.3, 13.6, 0),
    ('71cadbc3-8189-5e72-ab53-d32a0344e1d7', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '722ad53f-d206-509c-a394-20bba39e7d90', '0cab1e9f-8d2e-5024-9fe1-9ea6a172133e', null, 'Tam buğday ekmeği', 30, 'slice', 1, null, 74.1, 3.9, 12.3, 1, 2.1, 1),
    ('6df58b21-a122-5d0a-b1c3-86a886e4eea3', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'adb5bf9f-f9e4-5ad0-aa90-eece99e3acfd', null, 'ce6fe68f-4009-59ff-8481-923621dfc45e', 'Elmalı, tarçınlı süzme yoğurt', null, null, null, 1, 276.3, 16, 22.7, 14.8, 5.3, 0),
    ('e3ba4d65-4d59-526d-9659-7143e16e0f6e', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'de030006-d394-560e-bb40-5aacd310dcf6', null, '343786d4-823f-5280-9ae9-f8486571051b', 'Zeytinyağlı taze fasulye', null, null, null, 1, 146.7, 3.1, 13.6, 10.1, 4.6, 0),
    ('fc8dc165-0f14-5d91-b839-491759988865', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'a8b3ffbd-c164-584d-8697-8f3dead9fc7d', null, '9b0af6b0-397a-50ab-927d-8a627c1cb983', 'Süzme yoğurtlu gece yulafı', null, null, null, 1, 398, 21.1, 39.9, 18.2, 6.3, 0),
    ('2058d8fe-6d6a-5c8d-9e15-275a960d8a49', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'a8b3ffbd-c164-584d-8697-8f3dead9fc7d', '0cab1e9f-8d2e-5024-9fe1-9ea6a172133e', null, 'Tam buğday ekmeği', 30, 'slice', 1, null, 74.1, 3.9, 12.3, 1, 2.1, 1),
    ('2d1dd47f-a4d6-5f19-87af-b910f2cb5248', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '1f7f3f97-afe0-575e-ae17-165ed277272b', null, '68fecda7-80a2-5ad2-bee9-6059e478965a', 'Mercimek köftesi', null, null, null, 1, 290.8, 12.2, 46.4, 7.8, 8.4, 0),
    ('b2a67aab-b051-5435-a056-d497094cad5c', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '1f7f3f97-afe0-575e-ae17-165ed277272b', '0cab1e9f-8d2e-5024-9fe1-9ea6a172133e', null, 'Tam buğday ekmeği', 30, 'slice', 1, null, 74.1, 3.9, 12.3, 1, 2.1, 1),
    ('5b445117-97a0-509a-a227-3dd7377a3996', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '9021d3a2-d1f6-5160-9175-96aaa07e2b6e', null, 'bda683e7-26ac-53ac-9486-de9ee4253c5f', 'Fırında baharatlı nohut', null, null, null, 1, 230, 10.9, 33.6, 6.6, 9.5, 0),
    ('c3bffbd5-79fc-5465-9e7a-9592afa67999', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'cbacffaa-c734-5987-9f0c-5f5a320ceb66', null, '23d45a3e-ec05-5547-a44b-01fe1b82523c', 'Fırında limonlu somon ve kabak', null, null, null, 1, 422.4, 33.3, 11, 26.8, 3.1, 0),
    ('9a9e7e88-1fc8-530a-a261-e72a894f518b', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '2233892e-0b2e-5b4b-88ed-a2ae23b91fab', null, '395caa3a-20d2-55f1-9ef6-ad2c21bfe191', 'Menemen', null, null, null, 1, 204.5, 11.4, 9.2, 14.1, 2.8, 0),
    ('b017aab3-3f13-5b38-b0ee-4a358cc3ccbf', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '2233892e-0b2e-5b4b-88ed-a2ae23b91fab', '0cab1e9f-8d2e-5024-9fe1-9ea6a172133e', null, 'Tam buğday ekmeği', 30, 'slice', 1, null, 74.1, 3.9, 12.3, 1, 2.1, 1),
    ('699ccc5f-4c0e-54e6-a655-829cbae4ab12', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'eaa28ac4-fb9f-511a-975e-4670b3dafdc0', null, '2ecdbc53-5e3d-59b5-b223-0f8cb3e8f0e4', 'Sebzeli, nohutlu bulgur pilavı', null, null, null, 1, 267.2, 8.1, 44.4, 7.8, 8.6, 0),
    ('2705dc42-1663-5f92-9c73-6fa16b5f8b3e', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'eaa28ac4-fb9f-511a-975e-4670b3dafdc0', '0cab1e9f-8d2e-5024-9fe1-9ea6a172133e', null, 'Tam buğday ekmeği', 30, 'slice', 1, null, 74.1, 3.9, 12.3, 1, 2.1, 1),
    ('4a6ad946-f19a-5728-99be-ab63fe1299b0', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'dde4729e-3523-5f8e-a63d-d178d184d412', null, 'ce6fe68f-4009-59ff-8481-923621dfc45e', 'Elmalı, tarçınlı süzme yoğurt', null, null, null, 1, 276.3, 16, 22.7, 14.8, 5.3, 0),
    ('22c9e301-b25e-57b4-a7f8-424ed39c3857', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'aa1282d9-1ed8-5048-a8f9-a508e31f4683', null, 'df15333a-90d0-5b10-8011-89bbb352c405', 'Kırmızı mercimek çorbası', null, null, null, 1, 253, 12.2, 35.9, 7.8, 6.5, 0),
    ('0e01a10e-adf9-5ce6-8820-321c8037840a', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'b125b348-a26c-5132-8dc5-f795d11aa069', null, 'e7fbf28f-0734-55d3-b1fd-e1f54b181c7d', 'Çılbır', null, null, null, 1, 245.7, 16.4, 6.6, 17, 0.4, 0),
    ('2d1c9c7c-beaf-5def-bc9f-3b601f035cfc', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'b125b348-a26c-5132-8dc5-f795d11aa069', '0cab1e9f-8d2e-5024-9fe1-9ea6a172133e', null, 'Tam buğday ekmeği', 30, 'slice', 1, null, 74.1, 3.9, 12.3, 1, 2.1, 1),
    ('da0e2808-72fe-59bc-b149-9b5ca8ff3beb', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '9ac0d4cb-d522-50ed-9133-1a37db11514c', null, '23c9cd4c-4d42-5a1c-84a4-7ba0815d98a0', 'Nohutlu kinoa salatası', null, null, null, 1, 383.9, 14.9, 58.6, 11.7, 12, 0),
    ('bbfeda04-fd18-5cd8-8591-eadaf6a1049c', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '9ac0d4cb-d522-50ed-9133-1a37db11514c', '0cab1e9f-8d2e-5024-9fe1-9ea6a172133e', null, 'Tam buğday ekmeği', 30, 'slice', 1, null, 74.1, 3.9, 12.3, 1, 2.1, 1),
    ('ee392d9c-433e-56cb-9667-06d573acd007', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'def28902-6dce-5bf2-aa71-e28c4076e7af', null, 'bda683e7-26ac-53ac-9486-de9ee4253c5f', 'Fırında baharatlı nohut', null, null, null, 1, 230, 10.9, 33.6, 6.6, 9.5, 0),
    ('08545023-c313-5798-9c8d-3a730a03c6c6', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'bf92ecfa-070f-5ef0-820a-2e59f3e96935', null, 'b9507c06-8136-5950-bcd1-120f57d33429', 'Tavuklu sebze sote', null, null, null, 1, 292.5, 33.2, 16.6, 10.6, 4.5, 0),
    ('41aa7ad6-645b-5c41-ab48-6832661b0320', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '595d2fb5-1737-59b3-b266-8fea4fe63015', null, '9b0af6b0-397a-50ab-927d-8a627c1cb983', 'Süzme yoğurtlu gece yulafı', null, null, null, 1, 398, 21.1, 39.9, 18.2, 6.3, 0),
    ('ac5fe47d-f14b-57d2-b1ec-079f9a3320cb', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '595d2fb5-1737-59b3-b266-8fea4fe63015', '0cab1e9f-8d2e-5024-9fe1-9ea6a172133e', null, 'Tam buğday ekmeği', 30, 'slice', 1, null, 74.1, 3.9, 12.3, 1, 2.1, 1),
    ('78b2c4bf-5df6-5a59-adbb-4843b6132e28', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'f998614b-6fb7-5e1e-8735-aaa6e2f12d36', null, '343786d4-823f-5280-9ae9-f8486571051b', 'Zeytinyağlı taze fasulye', null, null, null, 1, 146.7, 3.1, 13.6, 10.1, 4.6, 0),
    ('f99eb61a-a088-5528-8a36-5c7c5d3298aa', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'f998614b-6fb7-5e1e-8735-aaa6e2f12d36', '0cab1e9f-8d2e-5024-9fe1-9ea6a172133e', null, 'Tam buğday ekmeği', 30, 'slice', 1, null, 74.1, 3.9, 12.3, 1, 2.1, 1),
    ('a75d329b-0bd0-58cd-8e2d-c78d8bd97d4e', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '5cf153f0-95e5-50cb-9282-648c6ce5cc1f', null, 'ce6fe68f-4009-59ff-8481-923621dfc45e', 'Elmalı, tarçınlı süzme yoğurt', null, null, null, 1, 276.3, 16, 22.7, 14.8, 5.3, 0),
    ('0b5684ef-b702-597a-bb3e-e37a5583cd78', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', '7ee0f54b-8986-5eaf-a3c3-3d3fb1d84713', null, '0a9df7e3-db0f-5cd9-b3c0-adee7b81f04c', 'Ton balıklı piyaz', null, null, null, 1, 433.5, 39.3, 52.7, 8.3, 13.6, 0);

  insert into public.share_links (id, owner_id, program_id, token, expires_at, show_client_name, allow_pdf, view_count, last_viewed_at) values
    ('8b8a49fc-2521-5c58-9367-472953841f4f', v_owner, '754274d3-6afe-5580-b37e-880bc48c494f', 'demo-share-token-7f3a9c2e41b8d6f05a1e3c9b7d2f4a6e8c0b1d3f5a7', now() + interval '30 days', true, true, 3, now() - interval '2 days');

  insert into public.leads (id, owner_id, kind, name, email, phone, message, payload, locale, consent_at, consent_version, status, created_at) values
    ('ee0f4674-5a50-5d61-bdc5-0ce56f27fb9f', v_owner, 'contact', 'Burcu (demo)', 'burcu.demo@example.com', null, 'Merhaba, iş yerinde öğle yemeklerini nasıl planlayabileceğimi konuşmak isterim.', '{"preferred":"email"}'::jsonb, 'tr', now() - interval '1 day', 'contact-2026-01', 'new', now() - interval '1 day'),
    ('8b348ea6-174f-5439-ab4b-ee221f6b48e7', v_owner, 'wizard', 'Omar (demo)', null, '+905550000010', null, '{"goal":"energy","activity":"light","habits":["skip_breakfast","low_water"],"time":"t15"}'::jsonb, 'ar', now() - interval '3 days', 'wizard-2026-01', 'new', now() - interval '3 days'),
    ('a7b2dfad-6542-5826-9627-9f9aceb6ce73', v_owner, 'professional', 'Dr. Elif (demo)', 'elif.demo@example.com', null, 'Endokrinoloji polikliniğinden danışan yönlendirmesi hakkında görüşmek isterim.', '{"profession":"Hekim","organization":"Demo Hastanesi"}'::jsonb, 'tr', now() - interval '6 days', 'pro-2026-01', 'contacted', now() - interval '6 days');

  insert into public.appointments (id, owner_id, client_id, title, starts_at, duration_min, kind, status, note) values
    ('782630ec-ab4e-547d-b592-c4f13235e93a', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', null, (current_date + 1)::timestamp + time '10:00' - interval '3 hours', 45, 'online', 'scheduled', null),
    ('57e7c769-334f-5db9-a084-390bd46c6d3e', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', null, (current_date + 2)::timestamp + time '14:30' - interval '3 hours', 45, 'in_person', 'scheduled', null),
    ('51b32e0f-7212-5b96-ab90-2d56f3b5f02c', v_owner, '82874080-9118-558c-a40b-6ebebb298afc', null, (current_date + 4)::timestamp + time '11:00' - interval '3 hours', 45, 'online', 'scheduled', null),
    ('3b3c8fd9-ab3e-54bc-8f39-b9a78b3aea5d', v_owner, 'e0dfed6d-9351-53a5-9efd-6960f459309f', null, (current_date + -5)::timestamp + time '09:30' - interval '3 hours', 45, 'in_person', 'done', null),
    ('b9d56894-eeee-5471-9abe-20f3973d4eb3', v_owner, '422ac089-f6c4-5897-87f6-99c47a01879d', null, (current_date + 8)::timestamp + time '16:00' - interval '3 hours', 45, 'phone', 'scheduled', null),
    ('13a3e8a9-c42f-5237-8ea2-072f73337745', v_owner, '422ac089-f6c4-5897-87f6-99c47a01879d', null, (current_date + 0)::timestamp + time '09:30' - interval '3 hours', 45, 'phone', 'scheduled', null),
    ('51d7b826-bd91-505a-838e-fcf17d437c5f', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', null, (current_date + 0)::timestamp + time '17:30' - interval '3 hours', 45, 'in_person', 'scheduled', null),
    ('2267e5c4-1ea9-5168-b666-08c3f41e5035', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', null, (current_date + -21)::timestamp + time '17:30' - interval '3 hours', 45, 'in_person', 'done', null),
    ('979ac51a-1bbb-5478-844e-fecf8e9dcc69', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', null, (current_date + -14)::timestamp + time '17:30' - interval '3 hours', 45, 'in_person', 'done', null),
    ('b1db40d7-2288-5f95-bd75-995edb4cd8ff', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', null, (current_date + -7)::timestamp + time '17:30' - interval '3 hours', 45, 'in_person', 'done', null);

  update public.clients set birth_date = (current_date + 2 - interval '40 years')::date where id = 'e0dfed6d-9351-53a5-9efd-6960f459309f';

  insert into public.tasks (id, owner_id, client_id, title, due_on, done_at) values
    ('44344199-d15c-5441-a46a-95613738f7c6', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', 'Kan tahlili sonuçlarını iste (demo)', current_date + -1, null),
    ('62682c90-f9cb-5a27-b41f-e5f03f3049f9', v_owner, '422ac089-f6c4-5897-87f6-99c47a01879d', 'Protein kaynakları listesini gönder (demo)', current_date + 1, null),
    ('4ce1fea7-65dd-5c55-bc08-1c2a9724bfe3', v_owner, null, 'Haftanın tarifini sitede paylaş (demo)', null, null);

  insert into public.client_packages (id, owner_id, client_id, name, sessions_total, starts_on, ends_on) values
    ('115ed2c5-f293-5256-9d66-e2c103bca7f2', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', '4 seanslık takip (demo)', 4, current_date - 28, null),
    ('6f2004ab-28f1-5b1e-bbf4-addad42d997b', v_owner, 'e0dfed6d-9351-53a5-9efd-6960f459309f', '8 seanslık sporcu programı (demo)', 8, current_date - 10, null),
    ('060939cd-2d62-5037-894d-4c09726009df', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', 'Aylık online takip (demo)', null, current_date - 25, current_date + 5);

  insert into public.lab_results (id, owner_id, client_id, taken_on, test, value, unit) values
    ('3ed8f435-6984-5718-bef0-395d3d4afd6f', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', current_date + -90, 'glucose_fasting', 108, 'mg/dL'),
    ('fc023eb1-fbd4-5797-a11b-5cbf3e42d91d', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', current_date + -90, 'insulin_fasting', 16, 'µIU/mL'),
    ('6cb52e05-9350-533b-8e05-a81dbac17e6b', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', current_date + -90, 'hba1c', 5.9, '%'),
    ('bb72803c-f3b2-51cd-b078-9c4f1bfc6ceb', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', current_date + -90, 'triglycerides', 190, 'mg/dL'),
    ('74278202-b0e2-547a-9fc7-8023eebfcdde', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', current_date + -10, 'glucose_fasting', 99, 'mg/dL'),
    ('48361113-892c-5c85-96de-c9d4641e18d6', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', current_date + -10, 'insulin_fasting', 12, 'µIU/mL'),
    ('033375ad-0f18-5d2d-bd2f-826562f1d822', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', current_date + -10, 'hba1c', 5.7, '%'),
    ('f2218242-2bb3-58c0-a36e-7c9529c133b1', v_owner, '6b2010b0-cd81-5359-9d4b-1e6ef7957fb4', current_date + -10, 'triglycerides', 160, 'mg/dL');

  -- client portal (local demo account for client:c1)
  if exists (select 1 from auth.users where id = '00000000-0000-4000-8000-000000000002') then
    update public.clients
       set user_id = '00000000-0000-4000-8000-000000000002', portal_consent_at = now() - interval '20 days', portal_consent_version = 'portal-2026-01'
     where id = '8c333d28-8e6c-5635-946c-1e3d9066554c';
    insert into public.client_habits (id, owner_id, client_id, label, position) values
      ('df793fa8-a640-5468-ad62-2e9b7f52ca5c', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', 'Kahvaltı yap', 0),
      ('aafb9a67-5eeb-5249-972f-f57e4f8b38ad', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', 'Her öğünde sebze', 1),
      ('259a6355-af21-5e2d-b5d6-1c02ea878665', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '30 dk yürüyüş', 2),
      ('b78cb46d-4ba8-51c8-a510-0334b57d9a82', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '22:00''den sonra atıştırma yok', 3);
    insert into public.checkins (id, owner_id, client_id, day, weight_kg, water_ml, habits, energy, note, updated_at) values
      ('937c79b5-1654-523f-ab1f-c1b2ed9b6f9c', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 13, 66.8, 2250, '{"df793fa8-a640-5468-ad62-2e9b7f52ca5c","aafb9a67-5eeb-5249-972f-f57e4f8b38ad","b78cb46d-4ba8-51c8-a510-0334b57d9a82"}'::text[]::uuid[], 4, null, least(((current_date - 13) + time '21:30') at time zone 'Europe/Istanbul', now())),
      ('d69891bd-d8d5-5d91-ae37-11b5fad4440b', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 12, 67, 1500, '{"df793fa8-a640-5468-ad62-2e9b7f52ca5c","aafb9a67-5eeb-5249-972f-f57e4f8b38ad","259a6355-af21-5e2d-b5d6-1c02ea878665"}'::text[]::uuid[], 3, null, least(((current_date - 12) + time '21:30') at time zone 'Europe/Istanbul', now())),
      ('105e7ba2-2b65-57a0-a2ff-5f576c3984e5', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 11, 66.7, 2000, '{"df793fa8-a640-5468-ad62-2e9b7f52ca5c","259a6355-af21-5e2d-b5d6-1c02ea878665","b78cb46d-4ba8-51c8-a510-0334b57d9a82"}'::text[]::uuid[], 4, null, least(((current_date - 11) + time '21:30') at time zone 'Europe/Istanbul', now())),
      ('5ccac998-b3b1-51e5-b795-912bda1adf93', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 10, 66.6, 1250, '{"df793fa8-a640-5468-ad62-2e9b7f52ca5c","aafb9a67-5eeb-5249-972f-f57e4f8b38ad","b78cb46d-4ba8-51c8-a510-0334b57d9a82"}'::text[]::uuid[], 4, null, least(((current_date - 10) + time '21:30') at time zone 'Europe/Istanbul', now())),
      ('47ce1532-4200-5947-abd0-b978b5399826', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 8, 66.5, 2250, '{"df793fa8-a640-5468-ad62-2e9b7f52ca5c","259a6355-af21-5e2d-b5d6-1c02ea878665","b78cb46d-4ba8-51c8-a510-0334b57d9a82"}'::text[]::uuid[], 4, null, least(((current_date - 8) + time '21:30') at time zone 'Europe/Istanbul', now())),
      ('298a7e04-c06f-5c61-ab70-e0ad8d733149', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 7, 66.5, 1500, '{"df793fa8-a640-5468-ad62-2e9b7f52ca5c","aafb9a67-5eeb-5249-972f-f57e4f8b38ad","b78cb46d-4ba8-51c8-a510-0334b57d9a82"}'::text[]::uuid[], 4, null, least(((current_date - 7) + time '21:30') at time zone 'Europe/Istanbul', now())),
      ('daa2897c-f7de-5401-9798-dbf3ab13eb18', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 6, 66.7, 2000, '{"df793fa8-a640-5468-ad62-2e9b7f52ca5c","aafb9a67-5eeb-5249-972f-f57e4f8b38ad","259a6355-af21-5e2d-b5d6-1c02ea878665"}'::text[]::uuid[], 3, 'Akşam biraz yorgundum ama yürüyüşü yaptım.', least(((current_date - 6) + time '21:30') at time zone 'Europe/Istanbul', now())),
      ('4c00163e-d6b2-5400-8280-53cd1b685269', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 5, 66.4, 1250, '{"df793fa8-a640-5468-ad62-2e9b7f52ca5c","259a6355-af21-5e2d-b5d6-1c02ea878665","b78cb46d-4ba8-51c8-a510-0334b57d9a82"}'::text[]::uuid[], 4, null, least(((current_date - 5) + time '21:30') at time zone 'Europe/Istanbul', now())),
      ('6206e23b-429c-5d65-9398-c4c1ea442625', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 3, 66.5, 2250, '{"df793fa8-a640-5468-ad62-2e9b7f52ca5c","aafb9a67-5eeb-5249-972f-f57e4f8b38ad","259a6355-af21-5e2d-b5d6-1c02ea878665"}'::text[]::uuid[], 3, null, least(((current_date - 3) + time '21:30') at time zone 'Europe/Istanbul', now())),
      ('a4b22f46-5fc4-5b7e-8a50-0a3683793840', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 2, 66.2, 1500, '{"df793fa8-a640-5468-ad62-2e9b7f52ca5c","259a6355-af21-5e2d-b5d6-1c02ea878665","b78cb46d-4ba8-51c8-a510-0334b57d9a82"}'::text[]::uuid[], 4, null, least(((current_date - 2) + time '21:30') at time zone 'Europe/Istanbul', now())),
      ('9f703a07-ac94-598a-8b15-b93416c78370', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 1, 66.2, 2000, '{"df793fa8-a640-5468-ad62-2e9b7f52ca5c","aafb9a67-5eeb-5249-972f-f57e4f8b38ad","b78cb46d-4ba8-51c8-a510-0334b57d9a82"}'::text[]::uuid[], 4, null, least(((current_date - 1) + time '21:30') at time zone 'Europe/Istanbul', now()));
    insert into public.diary_meals (id, owner_id, client_id, eaten_on, slot, time_label, note, updated_at) values
      ('14c065d5-b21f-5597-b385-9a18eeaef179', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 2, 'breakfast', '08:10', null, least(((current_date - 2) + time '08:10' + interval '20 minutes') at time zone 'Europe/Istanbul', now())),
      ('98a0ff00-b04a-5431-8fb1-fd276d4a3e8a', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 2, 'lunch', '13:05', null, least(((current_date - 2) + time '13:05' + interval '20 minutes') at time zone 'Europe/Istanbul', now())),
      ('e47810da-4cb3-5916-a6e8-cb00f44f9036', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 2, 'snack_pm', '16:30', null, least(((current_date - 2) + time '16:30' + interval '20 minutes') at time zone 'Europe/Istanbul', now())),
      ('5b18c734-52ed-5e40-acb7-9526176b3f53', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 2, 'dinner', '19:40', 'Porsiyonu küçük tuttum.', least(((current_date - 2) + time '19:40' + interval '20 minutes') at time zone 'Europe/Istanbul', now())),
      ('1257d61b-d9f7-5f0a-8dab-0e60703a7375', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 1, 'breakfast', '08:25', null, least(((current_date - 1) + time '08:25' + interval '20 minutes') at time zone 'Europe/Istanbul', now())),
      ('13d6137f-51b6-506f-ab29-9018a815d919', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 1, 'lunch', '12:50', 'İş yerinde yedim.', least(((current_date - 1) + time '12:50' + interval '20 minutes') at time zone 'Europe/Istanbul', now())),
      ('de63914e-d6b4-5635-9e2d-392ed19485bf', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', current_date - 1, 'dinner', '20:00', null, least(((current_date - 1) + time '20:00' + interval '20 minutes') at time zone 'Europe/Istanbul', now()));
    insert into public.diary_items (id, owner_id, client_id, meal_id, food_id, name, unit_key, unit_qty, position) values
      ('c8d4860b-6b24-5a0b-916a-804b9f6ad22d', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '14c065d5-b21f-5597-b385-9a18eeaef179', '8bd9dd84-2af0-56e8-82ae-71cb180fe214', 'Yulaf ezmesi', 'tbsp', 4, 0),
      ('20fb5c47-ea13-5737-8c3f-fea50ed0a106', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '14c065d5-b21f-5597-b385-9a18eeaef179', 'f8c7eb3c-f029-50cb-8a55-17b2206c2e1e', 'Yoğurt', 'bowl', 1, 1),
      ('0a422e39-eebb-585f-ae03-f417bf3067aa', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '14c065d5-b21f-5597-b385-9a18eeaef179', 'e9f8c5e7-014e-55b8-9ef6-5900e28e36da', 'Çilek', 'cup', 1, 2),
      ('172daea1-0f25-5b48-a09c-bd430d8888fb', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '98a0ff00-b04a-5431-8fb1-fd276d4a3e8a', '6c1f515b-fbce-5d03-8be0-836237e7fc60', 'Kırmızı mercimek (çiğ)', 'cup', 0.5, 0),
      ('bb88b2dc-bdbb-5407-9dcb-d914e1cb09f5', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '98a0ff00-b04a-5431-8fb1-fd276d4a3e8a', '0cab1e9f-8d2e-5024-9fe1-9ea6a172133e', 'Tam buğday ekmeği', 'slice', 1, 1),
      ('acf6b115-4dfb-5d2f-b175-37f306251c26', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '98a0ff00-b04a-5431-8fb1-fd276d4a3e8a', null, 'Mevsim salatası', null, null, 2),
      ('6d677675-e77c-5c3f-82b1-58d78d9791c0', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', 'e47810da-4cb3-5916-a6e8-cb00f44f9036', '64ed9190-0b1b-54f9-ae9a-29d0e26dc983', 'Elma', 'piece', 1, 0),
      ('bfc63af3-11a3-5efd-9feb-c5858e39c0e5', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', 'e47810da-4cb3-5916-a6e8-cb00f44f9036', '828338fd-b4fe-59c6-bf14-12a3897f0740', 'Ceviz içi', 'piece', 3, 1),
      ('11debd31-eabe-5d5c-a06c-90799a552e4e', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '5b18c734-52ed-5e40-acb7-9526176b3f53', '819d5300-0747-50df-83fa-1eded890e84b', 'Tavuk göğsü (çiğ)', 'portion', 1, 0),
      ('ed120e65-2e0b-51e6-8fa3-858a5e457fe0', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '5b18c734-52ed-5e40-acb7-9526176b3f53', '9e8ac249-f319-5deb-aff1-c9da38c65efd', 'Pilavlık bulgur', 'tbsp', 5, 1),
      ('578f23d0-9fc1-5b78-8881-da9c4e536856', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '5b18c734-52ed-5e40-acb7-9526176b3f53', 'f8c7eb3c-f029-50cb-8a55-17b2206c2e1e', 'Yoğurt', 'tbsp', 3, 2),
      ('94b9e2c5-928f-5f5b-b5f3-ed8d104be0b6', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '1257d61b-d9f7-5f0a-8dab-0e60703a7375', 'abf979f7-7277-5fd1-881a-122077d0fdb9', 'Yumurta', 'piece', 2, 0),
      ('dd27f880-0584-5b57-8d72-270f3793903a', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '1257d61b-d9f7-5f0a-8dab-0e60703a7375', 'e93c5fda-9a54-56c5-8bc9-8ed5a86d570d', 'Beyaz peynir', 'slice', 1, 1),
      ('ecd5df67-a0e3-533b-87eb-e9b13c814fa8', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '1257d61b-d9f7-5f0a-8dab-0e60703a7375', 'c62cfa3f-0417-5335-82f6-1339a13cb1a2', 'Domates', 'piece', 1, 2),
      ('f02220d6-7b1f-512c-8831-2304be655375', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '1257d61b-d9f7-5f0a-8dab-0e60703a7375', '0cab1e9f-8d2e-5024-9fe1-9ea6a172133e', 'Tam buğday ekmeği', 'slice', 1, 3),
      ('650a7c9e-8a6c-58d2-9583-59585ff7ab45', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', '13d6137f-51b6-506f-ab29-9018a815d919', null, 'Tavuklu wrap (kafeterya)', null, null, 0),
      ('d5e9fe79-a3c9-5e51-9adf-ffc481b7720f', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', 'de63914e-d6b4-5635-9e2d-392ed19485bf', '7b028dc0-4569-5b47-b5c5-2eecb29be9a1', 'Somon', 'portion', 1, 0),
      ('b106a835-cc45-5618-91fe-c3652a84e8d6', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', 'de63914e-d6b4-5635-9e2d-392ed19485bf', '87da5e05-229a-5924-b260-41d225846e2d', 'Kabak', 'piece', 1, 1),
      ('b0797e26-84ca-592d-8faf-24192162654b', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', 'de63914e-d6b4-5635-9e2d-392ed19485bf', '7a82a131-7f02-5e55-b841-25b2d3c11b01', 'Zeytinyağı', 'tbsp', 1, 2);
    insert into public.messages (id, owner_id, client_id, author, body) values
      ('f0bef8c4-d114-591b-b4cc-ad76339cec32', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', 'client', 'Akşam yemeğinden sonra tatlı isteği geliyor. Ne önerirsiniz?'),
      ('00cec026-e61d-55aa-b5ea-74011c6cbdc1', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', 'dietitian', 'Akşama bir kase yoğurt ve tarçın ekleyelim. İkindi ara öğününü atlamamak da bu isteği azaltır.'),
      ('864d2c21-bde9-5290-a7b4-a8de6b238b89', v_owner, '8c333d28-8e6c-5635-946c-1e3d9066554c', 'client', 'Dün iş yerinde wrap yedim, porsiyon uygun muydu?');
    -- the message trigger stamps "now" on insert; spread the thread over the last days
    update public.messages set created_at = ((now() at time zone 'Europe/Istanbul')::date - 3 + time '21:40') at time zone 'Europe/Istanbul', read_at = ((now() at time zone 'Europe/Istanbul')::date - 2 + time '09:05') at time zone 'Europe/Istanbul' where id = 'f0bef8c4-d114-591b-b4cc-ad76339cec32';
    update public.messages set created_at = ((now() at time zone 'Europe/Istanbul')::date - 2 + time '09:12') at time zone 'Europe/Istanbul', read_at = ((now() at time zone 'Europe/Istanbul')::date - 2 + time '12:30') at time zone 'Europe/Istanbul' where id = '00cec026-e61d-55aa-b5ea-74011c6cbdc1';
    update public.messages set created_at = least(((now() at time zone 'Europe/Istanbul')::date - 0 + time '08:10') at time zone 'Europe/Istanbul', now() - interval '10 minutes') where id = '864d2c21-bde9-5290-a7b4-a8de6b238b89';
  end if;

end $demo$;
