/**
 * Generates supabase/seed.sql (public content) and supabase/local/demo.sql (fictional clients,
 * LOCAL DEMO ONLY) from the typed seed files, so there is one source of truth.
 * Run: node scripts/gen-seed.ts
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { seedArticles } from '../lib/content/seed/articles.ts';
import { seedFoods, type SeedFood } from '../lib/content/seed/foods.ts';
import { seedRecipes } from '../lib/content/seed/recipes.ts';
import { seedSettings } from '../lib/content/seed/settings.ts';
import { seedUid as uid } from '../lib/content/seed/ids.ts';

const root = path.resolve(import.meta.dirname, '..');
const LOCALES = ['tr', 'en', 'fr', 'ar'] as const;

const q = (s: string | null | undefined) => (s == null ? 'null' : `'${s.replace(/'/g, "''")}'`);
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const arr = (v: readonly string[]) => `${q(`{${v.map((x) => `"${x}"`).join(',')}}`)}::text[]`;
const n = (v: number | null | undefined) => (v == null ? 'null' : String(v));

const foodByKey = new Map<string, SeedFood>(seedFoods.map((f) => [f.key, f]));

function chunk(lines: string[]): string {
  return lines.join(',\n    ');
}

// ---------------------------------------------------------------------------
// seed.sql
// ---------------------------------------------------------------------------
const out: string[] = [];
out.push(`-- GENERATED by scripts/gen-seed.ts — edit lib/content/seed/*.ts instead.
-- Public content only (foods, recipes, guides, site settings). Owned by the first auth user,
-- so create the dietitian account BEFORE running this (see README).
do $seed$
declare
  v_owner uuid;
begin
  select id into v_owner from public.profiles where role = 'dietitian' order by created_at limit 1;
  if v_owner is null then
    raise exception 'No dietitian account found. Create the dietitian account first (KURULUM.md → Adım 4).';
  end if;
`);

out.push(`  insert into public.foods (id, owner_id, key, category, kcal, protein_g, carb_g, fat_g, fiber_g, flags, units, review_status, source) values
    ${chunk(
      seedFoods.map(
        (f) =>
          `(${q(uid(`food:${f.key}`))}, v_owner, ${q(f.key)}, ${q(f.category)}, ${n(f.kcal)}, ${n(f.p)}, ${n(f.c)}, ${n(f.f)}, ${n(f.fib)}, ${arr(f.flags ?? [])}, ${j(f.units ?? [])}, 'needs_review', 'seed: approximate reference values — verify')`,
      ),
    )}
  on conflict (owner_id, key) do nothing;
`);

out.push(`  insert into public.food_translations (food_id, locale, owner_id, name, translation_status) values
    ${chunk(
      seedFoods.flatMap((f) =>
        LOCALES.map(
          (l) =>
            `(${q(uid(`food:${f.key}`))}, '${l}', v_owner, ${q(f.names[l])}, '${l === 'tr' ? 'reviewed' : 'needs_review'}')`,
        ),
      ),
    )}
  on conflict (food_id, locale) do nothing;
`);

out.push(`  insert into public.recipes (id, owner_id, published, published_at, illustration, prep_min, cook_min, servings, meal_types) values
    ${chunk(
      seedRecipes.map(
        (r, i) =>
          `(${q(uid(`recipe:${r.key}`))}, v_owner, true, now() - interval '${i} days', ${q(r.illustration)}, ${r.prepMin}, ${r.cookMin}, ${r.servings}, ${arr(r.mealTypes)})`,
      ),
    )}
  on conflict (id) do nothing;
`);

out.push(`  insert into public.recipe_translations (recipe_id, locale, owner_id, slug, title, summary, steps, tips, translation_status) values
    ${chunk(
      seedRecipes.flatMap((r) =>
        LOCALES.map((l) => {
          const t = r.text[l];
          return `(${q(uid(`recipe:${r.key}`))}, '${l}', v_owner, ${q(t.slug)}, ${q(t.title)}, ${q(t.summary)}, ${j(t.steps)}, ${q(t.tips ?? null)}, 'needs_review')`;
        }),
      ),
    )}
  on conflict (recipe_id, locale) do nothing;
`);

out.push(`  insert into public.recipe_ingredients (id, owner_id, recipe_id, food_id, grams, unit_key, unit_qty, optional, position) values
    ${chunk(
      seedRecipes.flatMap((r) =>
        r.ingredients.map((ing, i) => {
          if (!foodByKey.has(ing.food)) throw new Error(`Unknown food ${ing.food} in ${r.key}`);
          return `(${q(uid(`ri:${r.key}:${i}`))}, v_owner, ${q(uid(`recipe:${r.key}`))}, ${q(uid(`food:${ing.food}`))}, ${n(ing.grams)}, ${q(ing.unit ?? null)}, ${n(ing.qty)}, ${ing.optional ? 'true' : 'false'}, ${i})`;
        }),
      ),
    )}
  on conflict (id) do nothing;
`);

out.push(`  insert into public.articles (id, owner_id, published, published_at, illustration, category, reading_min, sources) values
    ${chunk(
      seedArticles.map(
        (a, i) =>
          `(${q(uid(`article:${a.key}`))}, v_owner, true, now() - interval '${i * 3} days', ${q(a.illustration)}, ${q(a.category)}, ${a.readingMin}, ${j(a.sources)})`,
      ),
    )}
  on conflict (id) do nothing;
`);

out.push(`  insert into public.article_translations (article_id, locale, owner_id, slug, title, excerpt, body, translation_status) values
    ${chunk(
      seedArticles.flatMap((a) =>
        LOCALES.map((l) => {
          const t = a.text[l];
          return `(${q(uid(`article:${a.key}`))}, '${l}', v_owner, ${q(t.slug)}, ${q(t.title)}, ${q(t.excerpt)}, ${q(t.body)}, 'needs_review')`;
        }),
      ),
    )}
  on conflict (article_id, locale) do nothing;
`);

out.push(`  insert into public.site_settings (key, owner_id, is_public, data) values
    ${chunk(Object.entries(seedSettings).map(([k, v]) => `(${q(k)}, v_owner, true, ${j(v)})`))}
  on conflict (key) do nothing;
end $seed$;
`);

writeFileSync(path.join(root, 'supabase', 'seed.sql'), out.join('\n'));

// ---------------------------------------------------------------------------
// local/demo.sql — FICTIONAL data for the local demo only. Never run against production.
// ---------------------------------------------------------------------------
type DemoClient = {
  key: string;
  name: string;
  email: string;
  phone: string;
  sex: 'female' | 'male' | 'other';
  birth: string;
  height: number;
  goal: string;
  goalWeight: number | null;
  activity: string;
  lang: string;
  status: string;
  tags: string[];
  startWeight: number;
  trend: number;
  weeks: number;
  allergies?: string;
  medical?: string;
};

const demoClients: DemoClient[] = [
  {
    key: 'c1',
    name: 'Deniz Aksoy (demo)',
    email: 'deniz.demo@example.com',
    phone: '+905550000001',
    sex: 'female',
    birth: '1991-04-12',
    height: 166,
    goal: 'Düzenli öğün saatleri, enerjinin gün içinde dengelenmesi.',
    goalWeight: 64,
    activity: 'light',
    lang: 'tr',
    status: 'active',
    tags: ['online', 'ofis'],
    startWeight: 71.2,
    trend: -0.35,
    weeks: 14,
    allergies: 'Laktoz intoleransı (hafif)',
    medical: 'Demo tıbbi not — paylaşım sayfasında görünmemeli.',
  },
  {
    key: 'c2',
    name: 'Emre Yıldız (demo)',
    email: 'emre.demo@example.com',
    phone: '+905550000002',
    sex: 'male',
    birth: '1986-09-30',
    height: 181,
    goal: 'Koşu antrenmanlarına uygun beslenme.',
    goalWeight: null,
    activity: 'active',
    lang: 'tr',
    status: 'active',
    tags: ['sporcu'],
    startWeight: 78.4,
    trend: 0.05,
    weeks: 10,
  },
  {
    key: 'c3',
    name: 'Layla Haddad (demo)',
    email: 'layla.demo@example.com',
    phone: '+905550000003',
    sex: 'female',
    birth: '1995-01-18',
    height: 160,
    goal: 'Aile sofrasını düzenlemek, sebze tüketimini artırmak.',
    goalWeight: 58,
    activity: 'moderate',
    lang: 'ar',
    status: 'active',
    tags: ['aile'],
    startWeight: 63.0,
    trend: -0.2,
    weeks: 8,
  },
  {
    key: 'c4',
    name: 'Camille Martin (demo)',
    email: 'camille.demo@example.com',
    phone: '+905550000004',
    sex: 'female',
    birth: '1989-06-03',
    height: 170,
    goal: 'Vejetaryen beslenmede protein dengesi.',
    goalWeight: null,
    activity: 'moderate',
    lang: 'fr',
    status: 'active',
    tags: ['vejetaryen', 'online'],
    startWeight: 61.5,
    trend: 0.02,
    weeks: 6,
  },
  {
    key: 'c5',
    name: 'Mert Kaya (demo)',
    email: 'mert.demo@example.com',
    phone: '+905550000005',
    sex: 'male',
    birth: '1979-11-22',
    height: 175,
    goal: 'Sürdürülebilir kilo kaybı, akşam atıştırmalarını azaltmak.',
    goalWeight: 84,
    activity: 'sedentary',
    lang: 'tr',
    status: 'active',
    tags: ['ofis'],
    startWeight: 96.8,
    trend: -0.45,
    weeks: 18,
    medical: 'Demo: hekim takibinde; ilaç bilgisi hekimde.',
  },
  {
    key: 'c6',
    name: 'Selin Öztürk (demo)',
    email: 'selin.demo@example.com',
    phone: '+905550000006',
    sex: 'female',
    birth: '1998-02-14',
    height: 163,
    goal: 'Kahvaltı alışkanlığı kazanmak.',
    goalWeight: null,
    activity: 'light',
    lang: 'en',
    status: 'paused',
    tags: [],
    startWeight: 55.0,
    trend: 0,
    weeks: 4,
  },
  {
    key: 'c7',
    name: 'Ahmet Demir (demo)',
    email: 'ahmet.demo@example.com',
    phone: '+905550000007',
    sex: 'male',
    birth: '1970-07-07',
    height: 172,
    goal: 'Tamamlandı: düzenli beslenme.',
    goalWeight: 80,
    activity: 'light',
    lang: 'tr',
    status: 'completed',
    tags: [],
    startWeight: 86.0,
    trend: -0.3,
    weeks: 20,
  },
];

function foodMacros(key: string, grams: number) {
  const f = foodByKey.get(key)!;
  const k = grams / 100;
  return { kcal: f.kcal * k, p: f.p * k, c: f.c * k, f: f.f * k, fib: f.fib * k };
}

function recipePerServing(key: string) {
  const r = seedRecipes.find((x) => x.key === key)!;
  const t = { kcal: 0, p: 0, c: 0, f: 0, fib: 0 };
  for (const ing of r.ingredients) {
    if (ing.optional) continue;
    const m = foodMacros(ing.food, ing.grams);
    t.kcal += m.kcal;
    t.p += m.p;
    t.c += m.c;
    t.f += m.f;
    t.fib += m.fib;
  }
  return {
    kcal: t.kcal / r.servings,
    p: t.p / r.servings,
    c: t.c / r.servings,
    f: t.f / r.servings,
    fib: t.fib / r.servings,
  };
}

const r1 = (x: number) => Math.round(x * 10) / 10;
const demo: string[] = [];
demo.push(`-- GENERATED by scripts/gen-seed.ts — FICTIONAL DEMO DATA for local mode only.
-- Never run against a production database.
do $demo$
declare
  v_owner uuid;
begin
  select id into v_owner from public.profiles where role = 'dietitian' order by created_at limit 1;
`);

const today = new Date();
const iso = (d: Date) => d.toISOString().slice(0, 10);

demo.push(`  insert into public.clients (id, owner_id, full_name, email, phone, birth_date, sex, height_cm, goal, goal_weight_kg, activity_level, allergies, medical_notes, preferred_language, status, tags, source, kvkk_consent_at, kvkk_consent_version, created_at) values
    ${chunk(
      demoClients.map(
        (c) =>
          `(${q(uid(`client:${c.key}`))}, v_owner, ${q(c.name)}, ${q(c.email)}, ${q(c.phone)}, ${q(c.birth)}, ${q(c.sex)}, ${c.height}, ${q(c.goal)}, ${n(c.goalWeight)}, ${q(c.activity)}, ${q(c.allergies ?? null)}, ${q(c.medical ?? null)}, '${c.lang}', '${c.status}', ${arr(c.tags)}, 'demo', now() - interval '${c.weeks * 7} days', 'kvkk-2026-01', now() - interval '${c.weeks * 7} days')`,
      ),
    )};
`);

const mRows: string[] = [];
for (const c of demoClients) {
  for (let w = 0; w <= c.weeks; w += 2) {
    const d = new Date(today);
    d.setDate(d.getDate() - (c.weeks - w) * 7 - (c.key === 'c1' ? 16 : 0));
    // gentle, noisy trend — never a steep line
    const noise = Math.sin(w * 1.7 + c.height) * 0.35;
    const weight = r1(c.startWeight + c.trend * w + noise);
    const fat =
      c.sex === 'male'
        ? r1(22 + c.trend * w * 0.4 + noise / 2)
        : r1(29 + c.trend * w * 0.4 + noise / 2);
    const waist = r1((c.sex === 'male' ? 92 : 78) + c.trend * w * 0.6 + noise);
    mRows.push(
      `(${q(uid(`m:${c.key}:${w}`))}, v_owner, ${q(uid(`client:${c.key}`))}, '${iso(d)}', ${weight}, ${fat}, ${waist}, ${r1(waist + 18)})`,
    );
  }
}
demo.push(`  insert into public.measurements (id, owner_id, client_id, measured_at, weight_kg, body_fat_pct, waist_cm, hip_cm) values
    ${chunk(mRows)};
`);

demo.push(`  insert into public.client_notes (id, owner_id, client_id, body, pinned, created_at) values
    (${q(uid('note:c1:1'))}, v_owner, ${q(uid('client:c1'))}, 'İlk görüşme: kahvaltıyı genellikle atlıyor, öğleden sonra enerji düşüşü yaşıyor. Hedef: önce saatleri sabitlemek.', true, now() - interval '98 days'),
    (${q(uid('note:c1:2'))}, v_owner, ${q(uid('client:c1'))}, 'Kahvaltı 5/7 gün yapılıyor. Akşam atıştırmaları azaldı. Sebze tüketimi hâlâ düşük.', false, now() - interval '40 days'),
    (${q(uid('note:c5:1'))}, v_owner, ${q(uid('client:c5'))}, 'Akşam 22:00 sonrası atıştırma alışkanlığı. İkindiye proteinli ara öğün eklendi.', true, now() - interval '60 days'),
    (${q(uid('note:c3:1'))}, v_owner, ${q(uid('client:c3'))}, 'Program Arapça hazırlanacak. Çocuklar için de uygun tarifler istiyor.', true, now() - interval '50 days');
`);

// A 7-day demo program for c1, built from recipes → macros computed here.
const slotMap: Record<string, string> = {
  breakfast: 'breakfast',
  lunch: 'lunch',
  snack: 'snack_pm',
  dinner: 'dinner',
};
const days = [
  [
    ['breakfast', 'overnight_oats'],
    ['lunch', 'quinoa_salad'],
    ['snack', 'apple_yogurt'],
    ['dinner', 'salmon_zucchini'],
  ],
  [
    ['breakfast', 'menemen'],
    ['lunch', 'lentil_soup'],
    ['snack', 'roasted_chickpeas'],
    ['dinner', 'chicken_saute'],
  ],
  [
    ['breakfast', 'cilbir'],
    ['lunch', 'tuna_piyaz'],
    ['snack', 'apple_yogurt'],
    ['dinner', 'green_beans'],
  ],
  [
    ['breakfast', 'overnight_oats'],
    ['lunch', 'lentil_kofte'],
    ['snack', 'roasted_chickpeas'],
    ['dinner', 'salmon_zucchini'],
  ],
  [
    ['breakfast', 'menemen'],
    ['lunch', 'bulgur_pilaf'],
    ['snack', 'apple_yogurt'],
    ['dinner', 'lentil_soup'],
  ],
  [
    ['breakfast', 'cilbir'],
    ['lunch', 'quinoa_salad'],
    ['snack', 'roasted_chickpeas'],
    ['dinner', 'chicken_saute'],
  ],
  [
    ['breakfast', 'overnight_oats'],
    ['lunch', 'green_beans'],
    ['snack', 'apple_yogurt'],
    ['dinner', 'tuna_piyaz'],
  ],
] as const;
const times: Record<string, string> = {
  breakfast: '08:00',
  lunch: '13:00',
  snack: '16:30',
  dinner: '19:30',
};

const programId = uid('program:c1');
demo.push(`  insert into public.programs (id, owner_id, client_id, title, language, status, starts_on, target_kcal, target_protein_g, target_carb_g, target_fat_g, notes, hydration) values
    (${q(programId)}, v_owner, ${q(uid('client:c1'))}, 'Eylül — düzenli öğünler', 'tr', 'active', current_date - 3, 1800, 90, 200, 60,
     'Öğün saatlerini sabit tutmaya çalış; bir öğünü kaçırırsan bir sonrakini büyütmek yerine planına dön.',
     'Her öğünden önce bir bardak su. Gün içinde toplam 8–10 bardak hedefle; çay ve kahveyi şekersiz tercih et.'),
    (${q(uid('program:tpl'))}, v_owner, null, 'Dengeli hafta', 'tr', 'draft', null, 1900, 95, 210, 65, null, null);
  update public.programs set is_template = true where id = ${q(uid('program:tpl'))};
  insert into public.program_days (id, owner_id, program_id, position, label) values
    ${Array.from({ length: 7 }, (_, i) => `(${q(uid(`tplday:${i}`))}, v_owner, ${q(uid('program:tpl'))}, ${i}, null)`).join(',\n    ')};
`);

const dRows: string[] = [];
const mealRows: string[] = [];
const itemRows: string[] = [];
days.forEach((meals, di) => {
  const dayId = uid(`pday:${di}`);
  dRows.push(`(${q(dayId)}, v_owner, ${q(programId)}, ${di}, null)`);
  meals.forEach(([slot, recipeKey], mi) => {
    const mealId = uid(`pmeal:${di}:${mi}`);
    mealRows.push(
      `(${q(mealId)}, v_owner, ${q(programId)}, ${q(dayId)}, '${slotMap[slot]}', ${mi}, '${times[slot]}', null)`,
    );
    const recipe = seedRecipes.find((r) => r.key === recipeKey)!;
    const m = recipePerServing(recipeKey);
    itemRows.push(
      `(${q(uid(`pitem:${di}:${mi}:0`))}, v_owner, ${q(programId)}, ${q(mealId)}, null, ${q(uid(`recipe:${recipeKey}`))}, ${q(recipe.text.tr.title)}, null, null, null, 1, ${r1(m.kcal)}, ${r1(m.p)}, ${r1(m.c)}, ${r1(m.f)}, ${r1(m.fib)}, 0)`,
    );
    if (slot === 'breakfast' || slot === 'lunch') {
      const bread = foodMacros('bread_whole', 30);
      itemRows.push(
        `(${q(uid(`pitem:${di}:${mi}:1`))}, v_owner, ${q(programId)}, ${q(mealId)}, ${q(uid('food:bread_whole'))}, null, 'Tam buğday ekmeği', 30, 'slice', 1, null, ${r1(bread.kcal)}, ${r1(bread.p)}, ${r1(bread.c)}, ${r1(bread.f)}, ${r1(bread.fib)}, 1)`,
      );
    }
  });
});
demo.push(`  insert into public.program_days (id, owner_id, program_id, position, label) values
    ${chunk(dRows)};
  insert into public.program_meals (id, owner_id, program_id, day_id, slot, position, time_label, note) values
    ${chunk(mealRows)};
  insert into public.program_meal_items (id, owner_id, program_id, meal_id, food_id, recipe_id, name, grams, unit_key, unit_qty, servings, kcal, protein_g, carb_g, fat_g, fiber_g, position) values
    ${chunk(itemRows)};
`);

demo.push(`  insert into public.share_links (id, owner_id, program_id, token, expires_at, show_client_name, allow_pdf, view_count, last_viewed_at) values
    (${q(uid('share:c1'))}, v_owner, ${q(programId)}, 'demo-share-token-7f3a9c2e41b8d6f05a1e3c9b7d2f4a6e8c0b1d3f5a7', now() + interval '30 days', true, true, 3, now() - interval '2 days');
`);

demo.push(`  insert into public.leads (id, owner_id, kind, name, email, phone, message, payload, locale, consent_at, consent_version, status, created_at) values
    (${q(uid('lead:1'))}, v_owner, 'contact', 'Burcu (demo)', 'burcu.demo@example.com', null, 'Merhaba, iş yerinde öğle yemeklerini nasıl planlayabileceğimi konuşmak isterim.', '{"preferred":"email"}'::jsonb, 'tr', now() - interval '1 day', 'contact-2026-01', 'new', now() - interval '1 day'),
    (${q(uid('lead:2'))}, v_owner, 'wizard', 'Omar (demo)', null, '+905550000010', null, '{"goal":"energy","activity":"light","habits":["skip_breakfast","low_water"],"time":"t15"}'::jsonb, 'ar', now() - interval '3 days', 'wizard-2026-01', 'new', now() - interval '3 days'),
    (${q(uid('lead:3'))}, v_owner, 'professional', 'Dr. Elif (demo)', 'elif.demo@example.com', null, 'Endokrinoloji polikliniğinden danışan yönlendirmesi hakkında görüşmek isterim.', '{"profession":"Hekim","organization":"Demo Hastanesi"}'::jsonb, 'tr', now() - interval '6 days', 'pro-2026-01', 'contacted', now() - interval '6 days');
`);

const apptRows: string[] = [];
[
  ['c1', 1, '10:00', 'online'],
  ['c5', 2, '14:30', 'in_person'],
  ['c3', 4, '11:00', 'online'],
  ['c2', -5, '09:30', 'in_person'],
  ['c4', 8, '16:00', 'phone'],
  // today: one in the morning, one late afternoon (the dashboard's agenda shows both states)
  ['c4', 0, '09:30', 'phone'],
  ['c5', 0, '17:30', 'in_person'],
  // Mert's last three weekly sessions (attended: his package is down to its last session)
  ['c5', -21, '17:30', 'in_person'],
  ['c5', -14, '17:30', 'in_person'],
  ['c5', -7, '17:30', 'in_person'],
].forEach(([c, dayOffset, time, kind], i) => {
  apptRows.push(
    `(${q(uid(`appt:${i}`))}, v_owner, ${q(uid(`client:${c}`))}, null, (current_date + ${dayOffset})::timestamp + time '${time}' - interval '3 hours', 45, '${kind}', '${Number(dayOffset) < 0 ? 'done' : 'scheduled'}', null)`,
  );
});
demo.push(`  insert into public.appointments (id, owner_id, client_id, title, starts_at, duration_min, kind, status, note) values
    ${chunk(apptRows)};
`);

// the dietitian's to-do list: one overdue, one for tomorrow, one without client or date
const taskRows = (
  [
    ['Kan tahlili sonuçlarını iste (demo)', 'c5', -1],
    ['Protein kaynakları listesini gönder (demo)', 'c4', 1],
    ['Haftanın tarifini sitede paylaş (demo)', null, null],
  ] as const
).map(
  ([title, c, offset], i) =>
    `(${q(uid(`task:${i}`))}, v_owner, ${c ? q(uid(`client:${c}`)) : 'null'}, ${q(title)}, ${offset == null ? 'null' : `current_date + ${offset}`}, null)`,
);
// a birthday two days from whenever the demo database is built (the dashboard's birthday card)
demo.push(`  update public.clients set birth_date = (current_date + 2 - interval '40 years')::date where id = ${q(uid('client:c2'))};
`);
demo.push(`  insert into public.tasks (id, owner_id, client_id, title, due_on, done_at) values
    ${chunk(taskRows)};
`);

// Packages (no prices or payments: amounts are the practice's own, never made up here) and two
// lab reports for Mert. Lab values are fictional and carry no reference range — a range is
// always copied from the lab's own report.
demo.push(`  insert into public.client_packages (id, owner_id, client_id, name, sessions_total, starts_on, ends_on) values
    (${q(uid('pkg:c5'))}, v_owner, ${q(uid('client:c5'))}, '4 seanslık takip (demo)', 4, current_date - 28, null),
    (${q(uid('pkg:c2'))}, v_owner, ${q(uid('client:c2'))}, '8 seanslık sporcu programı (demo)', 8, current_date - 10, null),
    (${q(uid('pkg:c1'))}, v_owner, ${q(uid('client:c1'))}, 'Aylık online takip (demo)', null, current_date - 25, current_date + 5);
`);
const labRows = (
  [
    [-90, 'glucose_fasting', 108, 'mg/dL'],
    [-90, 'insulin_fasting', 16, 'µIU/mL'],
    [-90, 'hba1c', 5.9, '%'],
    [-90, 'triglycerides', 190, 'mg/dL'],
    [-10, 'glucose_fasting', 99, 'mg/dL'],
    [-10, 'insulin_fasting', 12, 'µIU/mL'],
    [-10, 'hba1c', 5.7, '%'],
    [-10, 'triglycerides', 160, 'mg/dL'],
  ] as const
).map(
  ([offset, test, value, unit], i) =>
    `(${q(uid(`lab:c5:${i}`))}, v_owner, ${q(uid('client:c5'))}, current_date + ${offset}, '${test}', ${value}, ${q(unit)})`,
);
demo.push(`  insert into public.lab_results (id, owner_id, client_id, taken_on, test, value, unit) values
    ${chunk(labRows)};
`);

// ---------------------------------------------------------------------------
// Client portal demo: Deniz (client:c1) has a portal account (created in lib/db/pglite.ts as
// LOCAL_CLIENT_ID before this file runs), habits, 14 days of check-ins, two days of diary and a
// short message thread. Everything is fictional.
// ---------------------------------------------------------------------------
const LOCAL_CLIENT_ID = '00000000-0000-4000-8000-000000000002';
const c1 = uid('client:c1');
const habits = [
  'Kahvaltı yap',
  'Her öğünde sebze',
  '30 dk yürüyüş',
  "22:00'den sonra atıştırma yok",
];
const habitIds = habits.map((_, i) => uid(`habit:c1:${i}`));

const checkinRows: string[] = [];
// Home-scale weights continue from the latest clinic measurement (a home scale reads a bit higher).
const c1Demo = demoClients.find((c) => c.key === 'c1')!;
const lastClinicKg = c1Demo.startWeight + c1Demo.trend * c1Demo.weeks;
for (let back = 13; back >= 1; back--) {
  if (back === 9 || back === 4) continue; // a couple of missed days, like real life
  const weight = r1(
    lastClinicKg + 0.5 - (13 - back) * 0.05 + (back % 3 === 0 ? 0.2 : back % 2 === 0 ? -0.1 : 0),
  );
  const water = 1250 + ((back * 173) % 5) * 250;
  const done = habitIds.filter((_, i) => (back + i) % 3 !== 0 || i === 0);
  const energy = 3 + (back % 3 === 0 ? 0 : 1);
  const note = back === 6 ? q('Akşam biraz yorgundum ama yürüyüşü yaptım.') : 'null';
  checkinRows.push(
    `(${q(uid(`checkin:c1:${back}`))}, v_owner, ${q(c1)}, current_date - ${back}, ${weight}, ${water}, ${arr(done)}::uuid[], ${energy}, ${note}, least(((current_date - ${back}) + time '21:30') at time zone 'Europe/Istanbul', now()))`,
  );
}

type DemoItem = [food: string, unit: string, qty: number] | [freeText: string];
const diaryDays: {
  back: number;
  meals: { slot: string; time: string; note?: string; items: DemoItem[] }[];
}[] = [
  {
    back: 2,
    meals: [
      {
        slot: 'breakfast',
        time: '08:10',
        items: [
          ['oats', 'tbsp', 4],
          ['yogurt', 'bowl', 1],
          ['strawberry', 'cup', 1],
        ],
      },
      {
        slot: 'lunch',
        time: '13:05',
        items: [['lentils_red', 'cup', 0.5], ['bread_whole', 'slice', 1], ['Mevsim salatası']],
      },
      {
        slot: 'snack_pm',
        time: '16:30',
        items: [
          ['apple', 'piece', 1],
          ['walnut', 'piece', 3],
        ],
      },
      {
        slot: 'dinner',
        time: '19:40',
        note: 'Porsiyonu küçük tuttum.',
        items: [
          ['chicken_breast', 'portion', 1],
          ['bulgur', 'tbsp', 5],
          ['yogurt', 'tbsp', 3],
        ],
      },
    ],
  },
  {
    back: 1,
    meals: [
      {
        slot: 'breakfast',
        time: '08:25',
        items: [
          ['egg', 'piece', 2],
          ['feta', 'slice', 1],
          ['tomato', 'piece', 1],
          ['bread_whole', 'slice', 1],
        ],
      },
      {
        slot: 'lunch',
        time: '12:50',
        note: 'İş yerinde yedim.',
        items: [['Tavuklu wrap (kafeterya)']],
      },
      {
        slot: 'dinner',
        time: '20:00',
        items: [
          ['salmon', 'portion', 1],
          ['zucchini', 'piece', 1],
          ['olive_oil', 'tbsp', 1],
        ],
      },
    ],
  },
];
const diaryMealRows: string[] = [];
const diaryItemRows: string[] = [];
for (const day of diaryDays) {
  day.meals.forEach((meal, mi) => {
    const mealId = uid(`diary:c1:${day.back}:${meal.slot}`);
    diaryMealRows.push(
      `(${q(mealId)}, v_owner, ${q(c1)}, current_date - ${day.back}, '${meal.slot}', '${meal.time}', ${q(meal.note ?? null)}, least(((current_date - ${day.back}) + time '${meal.time}' + interval '20 minutes') at time zone 'Europe/Istanbul', now()))`,
    );
    meal.items.forEach((item, ii) => {
      const id = q(uid(`diaryitem:c1:${day.back}:${mi}:${ii}`));
      if (item.length === 1) {
        diaryItemRows.push(
          `(${id}, v_owner, ${q(c1)}, ${q(mealId)}, null, ${q(item[0])}, null, null, ${ii})`,
        );
      } else {
        const food = seedFoods.find((f) => f.key === item[0])!;
        diaryItemRows.push(
          `(${id}, v_owner, ${q(c1)}, ${q(mealId)}, ${q(uid(`food:${item[0]}`))}, ${q(food.names.tr)}, '${item[1]}', ${item[2]}, ${ii})`,
        );
      }
    });
  });
}

demo.push(`  -- client portal (local demo account for client:c1)
  if exists (select 1 from auth.users where id = '${LOCAL_CLIENT_ID}') then
    update public.clients
       set user_id = '${LOCAL_CLIENT_ID}', portal_consent_at = now() - interval '20 days', portal_consent_version = 'portal-2026-01'
     where id = ${q(c1)};
    insert into public.client_habits (id, owner_id, client_id, label, position) values
      ${habits.map((h, i) => `(${q(habitIds[i]!)}, v_owner, ${q(c1)}, ${q(h)}, ${i})`).join(',\n      ')};
    insert into public.checkins (id, owner_id, client_id, day, weight_kg, water_ml, habits, energy, note, updated_at) values
      ${checkinRows.join(',\n      ')};
    insert into public.diary_meals (id, owner_id, client_id, eaten_on, slot, time_label, note, updated_at) values
      ${diaryMealRows.join(',\n      ')};
    insert into public.diary_items (id, owner_id, client_id, meal_id, food_id, name, unit_key, unit_qty, position) values
      ${diaryItemRows.join(',\n      ')};
    insert into public.messages (id, owner_id, client_id, author, body) values
      (${q(uid('msg:c1:1'))}, v_owner, ${q(c1)}, 'client', 'Akşam yemeğinden sonra tatlı isteği geliyor. Ne önerirsiniz?'),
      (${q(uid('msg:c1:2'))}, v_owner, ${q(c1)}, 'dietitian', 'Akşama bir kase yoğurt ve tarçın ekleyelim. İkindi ara öğününü atlamamak da bu isteği azaltır.'),
      (${q(uid('msg:c1:3'))}, v_owner, ${q(c1)}, 'client', 'Dün iş yerinde wrap yedim, porsiyon uygun muydu?');
    -- the message trigger stamps "now" on insert; spread the thread over the last days
    update public.messages set created_at = ((now() at time zone 'Europe/Istanbul')::date - 3 + time '21:40') at time zone 'Europe/Istanbul', read_at = ((now() at time zone 'Europe/Istanbul')::date - 2 + time '09:05') at time zone 'Europe/Istanbul' where id = ${q(uid('msg:c1:1'))};
    update public.messages set created_at = ((now() at time zone 'Europe/Istanbul')::date - 2 + time '09:12') at time zone 'Europe/Istanbul', read_at = ((now() at time zone 'Europe/Istanbul')::date - 2 + time '12:30') at time zone 'Europe/Istanbul' where id = ${q(uid('msg:c1:2'))};
    update public.messages set created_at = least(((now() at time zone 'Europe/Istanbul')::date - 0 + time '08:10') at time zone 'Europe/Istanbul', now() - interval '10 minutes') where id = ${q(uid('msg:c1:3'))};
  end if;
`);

demo.push(`end $demo$;
`);

writeFileSync(path.join(root, 'supabase', 'local', 'demo.sql'), demo.join('\n'));
console.log(
  `seed.sql: ${seedFoods.length} foods, ${seedRecipes.length} recipes, ${seedArticles.length} guides; demo.sql: ${demoClients.length} clients`,
);
